#include "ezfadvance/cartridge_image_builder.hpp"

#include "ezfadvance/cartridge_format.hpp"

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace ezfadvance {
namespace {

using std::size_t;
using std::uint8_t;
using std::uint16_t;
using std::uint32_t;
using std::uint64_t;

static constexpr size_t PROGRAM_BLOCK = 0x10000;
static constexpr size_t CARD_HALF_SIZE = 0x1000000;
static constexpr size_t MAX_CARD_IMAGE = 0x2000000;
static constexpr uint32_t GBA_ROM_BASE = 0x08000000u;

static void write_le16(std::vector<uint8_t>& v, size_t off, uint16_t x)
{
    v.at(off) = static_cast<uint8_t>(x);
    v.at(off + 1) = static_cast<uint8_t>(x >> 8);
}

static uint32_t read_le32(const uint8_t* p)
{
    return CartridgeFormat::readLe32(p);
}

static void write_le32(std::vector<uint8_t>& v, size_t off, uint32_t x)
{
    v.at(off) = static_cast<uint8_t>(x);
    v.at(off + 1) = static_cast<uint8_t>(x >> 8);
    v.at(off + 2) = static_cast<uint8_t>(x >> 16);
    v.at(off + 3) = static_cast<uint8_t>(x >> 24);
}

static uint32_t align_up_u32(uint32_t x, uint32_t a)
{
    return (x + a - 1u) & ~(a - 1u);
}

static std::vector<uint8_t> decode_base64(const char* s)
{
    std::array<int, 256> table{};
    table.fill(-1);
    const std::string alphabet =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    for (size_t i = 0; i < alphabet.size(); ++i)
        table[static_cast<unsigned char>(alphabet[i])] = static_cast<int>(i);
    std::vector<uint8_t> out;
    uint32_t accum = 0;
    int bits = 0;
    for (const unsigned char c : std::string(s)) {
        if (c == '=') break;
        if (std::isspace(c)) continue;
        const int val = table[c];
        if (val < 0) throw std::runtime_error("invalid base64 character");
        accum = (accum << 6) | static_cast<uint32_t>(val);
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out.push_back(static_cast<uint8_t>((accum >> bits) & 0xFFu));
        }
    }
    return out;
}

// Single-ROM loader template captured from writeromonemptycard.pcap.
// Original load address: 0x0000D3B0, length 0x660.
// Relocation algorithm was validated byte-for-byte against the independent
// GBA-Notepad single-ROM capture.
static constexpr uint32_t SINGLE_TEMPLATE_BASE = 0x0000D3B0u;
static constexpr size_t SINGLE_TEMPLATE_LEN = 0x660;
static constexpr size_t SINGLE_HEADER_OFF = 0x4E8;
static constexpr size_t SINGLE_HEADER_COUNT2_OFF = 0x4F6;
static constexpr size_t SINGLE_ENTRY_OFF = 0x4F8;

// Multi-ROM loader/menu template captured from add3rom.pcap.
// v24 restores the exact v4-v8 capture-derived bytes; v9-v23 had 25
// accidental byte changes in this embedded template.
// Original load address: 0x0004A880, length 0x7080.
// The 28 bytes lost at the USBPcap 64 KiB snaplen boundary were recovered
// directly from a cartridge written by the original Windows EZ3Manager.
// They are patched explicitly at loader offset 0x5764 below.
// Everything else is directly capture-derived.
static constexpr uint32_t MULTI_TEMPLATE_BASE = 0x0004A880u;
static constexpr size_t MULTI_TEMPLATE_LEN = 0x7080;
static constexpr size_t MULTI_HEADER_OFF = 0x475E;
static constexpr size_t MULTI_ENTRY_OFF = 0x476E;
// The repeated 28-byte catalog-slot region ends at loader offset 0x548E.
// 4_4_4_4_8MB.pcap and 4_4_4_4_8_8MB.pcap prove entries 1..6 use this same
// structure. The base template contains empty sentinel entries beyond those
// used by the capture, so the writer may populate additional slots safely as
// long as it never crosses into the next loader data structure.
static constexpr size_t MULTI_CATALOG_END_OFF = 0x548E;
static constexpr size_t MULTI_CATALOG_MAX_ENTRIES =
    (MULTI_CATALOG_END_OFF - MULTI_ENTRY_OFF) / 28;
static_assert(MULTI_ENTRY_OFF + MULTI_CATALOG_MAX_ENTRIES * 28
              == MULTI_CATALOG_END_OFF,
              "multi-ROM catalog region must contain whole 28-byte entries");
static_assert(MULTI_CATALOG_MAX_ENTRIES == 120,
              "unexpected multi-ROM catalog slot count");

// kMultiTemplateB64 came from the original three-ROM capture, so its first
// three catalog slots contain captured entries. Later slots are already empty
// sentinels; additional ROMs overwrite those slots normally.
static constexpr size_t MULTI_TEMPLATE_POPULATED_ENTRY_SLOTS = 3;

// piano-bios.pcap proves that the original manager uses a slightly shorter
// two-ROM form of the multi-ROM loader/menu image.
//
// For two ROMs:
//   - the programmed loader/menu extent is 0x6F80 bytes, not 0x7080;
//   - bytes 0x6F26..0x6F7F are left erased (0xFF);
//   - the unused third catalog slot is encoded as:
//       00 + fifteen ASCII spaces + twelve 00 bytes.
//
// Absolute addresses for Piano + Bios_Dumper with loader @ 0x1A880:
//   erased tail begins 0x217A6
//   original manager stops programming at 0x21800.
static constexpr size_t MULTI_TWO_ROM_LEN = 0x6F80;
static constexpr size_t MULTI_TWO_ROM_ERASED_TAIL_OFF = 0x6F26;

// 8_8_8_8MiB.pcap, 4_4_4_4_8MB.pcap, and 4_4_4_4_8_8MB.pcap prove that
// the four-, five-, and six-ROM forms keep the full 0x7080 loader and
// zero-fill its final 26 bytes.
// The three-ROM capture leaves these bytes FF.
static constexpr size_t MULTI_FOUR_PLUS_ROM_ZERO_TAIL_OFF = 0x7066;
static constexpr size_t MULTI_FOUR_PLUS_ROM_ZERO_TAIL_LEN = 0x1A;

// Exact 28-byte loader gap recovered from a real cartridge programmed by
// the original Windows software (absolute 0x1FFE4 for Piano+Bios_Dumper,
// loader-relative offset 0x5764).  These bytes were invisible in USBPcap
// because each 64-KiB transfer was truncated by the capture snaplen.
static constexpr size_t MULTI_CAPTURE_GAP_OFF = 0x5764;
static constexpr std::array<uint8_t, 28> MULTI_CAPTURE_GAP_BYTES = {
    0x00,0x00,0x00,0x06,  // 0x06000000
    0x00,0x00,0x00,0x06,  // 0x06000000
    0x00,0x00,0x00,0x06,  // 0x06000000
    0x00,0x00,0x00,0x05,  // 0x05000000
    0x00,0x02,0x00,0x05,  // 0x05000200
    0x00,0x00,0x00,0x07,  // 0x07000000
    0x00,0x00,0x01,0x06   // 0x06010000
};

static const char kSingleTemplateB64[] =
    "BgAA6gBiYmJiAAAAAAAAAOgEAAAAAAAAAAAAAAAAAAAGAADqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAoOMA8CnhxNCf"
    "5R8AoOMA8CnhvNCf5QEAj+IQ/y/hLkkvSAhgL0hAAQrSeEZAAQzTQCMbA9oBFhyRAADwQPgwR0AhCQPIAQDwMPgDIAAGJUkA8Cv4"
    "JUglSQkaAPAm+CRJJUolTADwKvglSSVKJkwA8CX4JUomSVMaAtAlSgDwH/glSSVKJkwA8Bn4JUomSVMaAtAlSgDwE/gAIAAhJEue"
    "RiRLGEcAR8BGwEYDIokYkUMD0AAiBMAEOfzRcEejGgMgGxiDQwPQAckBwgQ7+9FwRwAAoH8AAwB/AAP8fwADAAUAA7DTAAjweQAA"
    "TAYAA/gGAAMQ2gAI+AYAA/gGAAPE2AAIAAUAA0wGAAMQ2gAIENoACPgGAAMQ2gAIAAAAAgAAAAIQ2gAIENoACAAAAALw0wAIKNUA"
    "CA3AoOFw2C3poDGf5aBhn+UEsEziBACg4wAwhuVpAADrVTzg4wBQoOMCw6DjqjBD4rAwzOEA4JblAFCM5bBQzOETIN7ltjHe4QMo"
    "guBkMZ/lVRyg4wAgg+UOBKDjVTDg46oQgeKwEMzhVSCg4wBQjOWwUMzhADDA5QwwoOMAIMDlATDA5QBQwOUAUMDlFDDe5QMwQ+L/"
    "MBPiBUCg4RghnwUCO6ADPwAACgEAU+MIIZ8FATugAzsAAAoCAFPj+CCfBQY8oAM3AAAKAwBT4+ggnwWwUMIBAgAACgQAU+PYIJ8V"
    "LgAACrAw0uEBMIPjABCW5bAwwuG6IdHhuDHR4bwAn+UCOIPgAjOD4gAwgOUAMKDjAROg4wMgoOEBMIPiAzig4VUIU+MBIMHkQzig"
    "4fn//5oBE6DjQy+g47AQgeKwMKDjAyCC4gDAoOMBMIPiAzig4SMIUuEBwMHkQzig4fn//yoBE6DjfzDg4wAwweUBIKDhATCg4yEQ"
    "geIAMMHlNzDC5ScwwuUxMMLlNDCf5QAAkOUP4KDhE/8v4XBoG+ke/y/hFCCf5QE6oOOwMMLhzP//6qjYAAhgBgADgAYAA7AGAAOg"
    "BgADEAYAAwTgLeVVPKDjAMCg4wIjoOOqMIPisDDC4Q4UoOMAwILl/wAA4rDAwuFVMODjVSCg4wzgoOEAMMHlACDB5QEAweUAwMHl"
    "AMDB5QTgneQe/y/hHv8v4QEzoOOCP4PiACCg47AQ0+EcAJ/lsCDD4RgQn+UBMILiAhGA5/8gA+INAFLj+v//mh7/L+HABgADQNcA"
    "CAHDoOMCzIzisCDc4f8AAOIBMKDjEyCC4Wwwn+UCAFDjsCDM4QARg+cBI6DjBgAAigEAUOMRAAAKCwAAygAAUOO0MNIBCDCDAwUA"
    "AAoBI6Djgi+C4rAw0uEBMIPjsDDC4R7/L+G0MMLh9///6gIAUOP1//8atDDS4SAwg+P4///qtDDS4RAwg+P1///qwAYAAwEToOMC"
    "HIHisCDR4f88oOP/AADi/jCD4hMgAuACAFDjsCDB4QEjoOMGAACKAQBQ4w8AAAoJAADKAABQ47Qw0gEIMMMDAwAACjAgn+UwMJ/l"
    "ACGD5x7/L+G0MMLh+f//6gIAUOP3//8atDDS4SAww+P4///qtDDS4RAww+P1///qQNcACMAGAAMBAAAAAAAAAAAAAAAAAAEAcGlh"
    "bm8AAAAAAAAAAAAAAAAAAAkDAAAAwAAAAAEjoOMAMrLluBDS4QAAT+EHQC3pAQCg47gAwuEjGAPg5MCf5QEAEeIlAAAaBMCM4gIA"
    "EeIiAAAaBMCM4gQAEeIfAAAaBMCM4ggAEeIcAAAaBMCM4hAAEeIZAAAaBMCM4iAAEeIWAAAaBMCM4kAAEeITAAAaBMCM4oAAEeIQ"
    "AAAaBMCM4gEMEeINAAAaBMCM4gIMEeIKAAAaBMCM4gELEeIHAAAaBMCM4gILEeIEAAAaBMCM4gEKEeIBAAAaBMCM4gIKEeKyAMLh"
    "ADAP4d8ww+MfMIPjA/Ap4QAAnOUAQC3pAOCP4hD/L+EAQL3oADAP4d8ww+OSMIPjA/Ap4QdAvei4EMLhAPBp4R7/L+HABgADVTzg"
    "4wIToOOqMEPisDDB4Rwgn+UcMJ/lAMCS5bAg0+EAwIHlsCDB4QAwoOEA8KDhHv8v4YAGAAOwBgAD";

static const char kMultiTemplateB64[] =
    "BgAA6gBiYmJiAAAAAAAAAF5HAAAAAAAAAAAAAAAAAAAGAADqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAoOMA8CnhxNCf"
    "5R8AoOMA8CnhvNCf5QEAj+IQ/y/hLkkvSAhgL0hAAQrSeEZAAQzTQCMbA9oBFhyRAADwQPgwR0AhCQPIAQDwMPgDIAAGJUkA8Cv4"
    "JUglSQkaAPAm+CRJJUolTADwKvglSSVKJkwA8CX4JUomSVMaAtAlSgDwH/glSSVKJkwA8Bn4JUomSVMaAtAlSgDwE/gAIAAhJEue"
    "RiRLGEcAR8BGwEYDIokYkUMD0AAiBMAEOfzRcEejGgMgGxiDQwPQAckBwgQ7+9FwRwAAoH8AAwB/AAP8fwADAAUAA4CoBAjweQAA"
    "TAYAAzoNAANI/wQIPA0AAwAOAAP8/QQIAAUAA0wGAAMMAAUIDAAFCAAOAAMMAAUIAAAAAgAAAAIMAAUIDAAFCAAAAALAqAQIHLkE"
    "CAIooOH/EAHiEEAt6UIooOEAQKDhAwBR4wHxn5cbAADqKKoECHiqBAiAqgQIiKoECGAwn+UA4JPlAjig4SMIoOEAEKDjAABR4QoA"
    "ACoBwKDhATCB4gM4oOFDGKDhASig4aw3oOEiCFDhAsCg4bQgk+G+IIPh9f//ihBAvege/y/hFDCf5er//+oQMJ/l6P//6gwwn+Xm"
    "///qPA0AA0ANAANEDQADSA0AA/8AAOLwQS3p/yAC4v+AAeL/YAPiHwBQ4wDxn5d6AADqQKsECLyrBAjEqwQIzKsECNSrBAjcqwQI"
    "5KsECOyrBAj0qwQI/KsECASsBAgMrAQIFKwECBysBAgkrAQILKwECDSsBAg8rAQIRKwECEysBAhUrAQIXKwECGSsBAhsrAQIdKwE"
    "CHysBAiErAQIjKwECJSsBAicrAQIpKwECKysBAhsMZ/lAFCg4wIAVeEAEJPlFwAAKgJwoOEIQKDhAMCg4wQAXOENAAAqBTig4SM4"
    "oOGYAw7gDACg4QEwjOIDOKDhQ8ig4QwooOEgOI7ggzCg4SIIVOECAKDhsWCD4fX//4oBMIXiAzig4SMIV+FDWKDh6f//ivBBvege"
    "/y/h9DCf5d///+rwMJ/l3f//6uwwn+Xb///q6DCf5dn//+rkMJ/l1///6uAwn+XV///q3DCf5dP//+rYMJ/l0f//6tQwn+XP///q"
    "0DCf5c3//+rMMJ/ly///6sgwn+XJ///qxDCf5cf//+rAMJ/lxf//6rwwn+XD///quDCf5cH//+q0MJ/lv///6rAwn+W9///qrDCf"
    "5bv//+qoMJ/luf//6qQwn+W3///qoDCf5bX//+qcMJ/ls///6pgwn+Wx///qlDCf5a///+qQMJ/lrf//6owwn+Wr///qiDCf5an/"
    "/+qEMJ/lp///6oAwn+Wl///qfDCf5aP//+pMDQADUA0AA1QNAANYDQADXA0AA2ANAANkDQADaA0AA2wNAANwDQADdA0AA3gNAAN8"
    "DQADgA0AA4QNAAOIDQADjA0AA5ANAAOUDQADmA0AA5wNAAOgDQADpA0AA6gNAAOsDQADsA0AA7QNAAO4DQADvA0AA8ANAAPEDQAD"
    "yA0AAw3AoOEw2C3pAFig4QBAoOMlCFThBLBM4gEAADowaBvpHv8v4TgAAOsBMITiAzig4QUAU+FDSKDh+f//Ovb//+pCL6DjEEAt"
    "6UPPoOMB46DjgSOC4oJAoOOwQMLhDDCO4ABAoOOBw4ziQu+O4oQgoOOwIMzhARig4QAIoOGwQM7hsEDD4UEYoOEDwKDhIAig4bAw"
    "3OEAAFPh/P//OgEzoONCP4PiPwbg4wDgoOMBKKDhPwxA4rDgw+EDwKDhIhig4QIAQOKwINzhkEKD4AM1oOEjCFHh+v//ikI/oOND"
    "L6DjAROg4wDgoOOBM4PigSOC4kMfgeKw4MPhsODC4bDgzOGw4MHhEEC96B7/L+EBI6DjtDDS4QEAE+P8//8aASOg47Qw0uEBABPj"
    "/P//Ch7/L+HwQS3pQu+g40NPoOMBU6DjgjCg44HjjuKwMM7hBMCF4AAwoOOBQ4TiQl+F4oSAoOOwgMThsDDF4bAwzOGwMNzhAQBT"
    "4QJgoOENAACqADGf5QAgk+UAMJLlADAT4LAwzgGwMMQBsDDFAbAwzAE2AAAKAcOg40PPjOKwMNzhAQBT4fP//7oBw6DjQs+M4gCA"
    "oOOwgMzhPzbg47AQ3OE/PEPiAjBD4pPhguACJaDhIghW4RgAANqYMJ/lQk+g40NfoOMBc6DjAOCT5YFDhOKBU4XiQ3+H4gAwnuU/"
    "FuDjADAT4D8cQeKwMMQBAhBB4rAwxQGwMMwBsDDHARMAAAoBw6DjQs+M4rAg3OGRgoPgAzWg4SMIVuHu///KAROg4wEAoOFCP6Dj"
    "Qy+g4wDAoOOBM4PigSOC4kIfgeJDD4DisMDD4bDAwuGwwMHhsMDA4fBBvege/y/h0A0AAw3AoOEw2C3pBLBM4ljQTeJsQEviADCg"
    "4UgQn+UEAKDhVSCg4/9QA+KxBwDrbDBb5QAAU+MAAKDjBwAACgUAU+EBIIDiAUCE4gQAAAoAMNTlAABT4/8AAuL3//8aAACg4zBo"
    "G+ke/y/hcP0ECA3AoOHw3y3pBLBM4pjQTeICUKDhACDS5QEYoOEAAFLjAAig4Qgg2+UDoKDhQZig4Qww2+UEENvlAGCg40AIoOGs"
    "IAvlpAAL5agQC+WwMAvlBoCg4QZwoOEAIKADDgAACgYgoOEiOKDhAwDV5yjAS+KDQIzgxv//6wEwhuIDOKDhQ2ig4QYooOEiONXn"
    "/wAA4gAAU+O4B0Th8f//GgBgoOMiGKDhAQBW4bggC+U9AAAqCZig4aTgG+XAkAvlDuig4bAgG+XAMBvlvOAL5QKWoOEjCKDhBiCg"
    "4S5YoOEIyKDhLAhR4RQAAIoiyKDhKOBL4owwjuC6F1PhAABR4wEwhwIDOKABAYCgAUN4oAF0AAAKuDdT4QAAU+NCKKARDECgEUkA"
    "ABoBMIfiAzig4QLBoONDeKDhAIDg48zHoOGoEBvlrDAb5QAAUeMAAFMTFwAACijgS+KiN47gByig4SIogOC4F1PhgiKF4CwoguAJ"
    "EIHhgiCg4QMbgeO6EILhATCG4gM4oOFDaKDhuDAb5QYooOEjGKDhATCI4gM4oOEiCFHhQ4ig4cz//4rwbxvpHv8v4agQG+UAAFHj"
    "CgAACijgS+KiN47gByig4SIogOC4F1PhgiKF4CwoguAJEIHhgiCg4QEbgePj///qrBAb5QAAUeMKAAAKKOBL4qI3juAHKKDhIiiA"
    "4LgXU+GCIoXgLCiC4AkQgeGCIKDhAhuB49X//+oHOKDhKOBL4iM4gOCiF47guCdR4YMyheAsOIPggzCg4QkgguG6IIPhy///6gEw"
    "QuIDOKDhQyig4fv//xoBIILiAjig4SMIVOG0IAvlQ8ig4RMAAJoHKKDhwBAb5SI4oOEhOIPgvBAb5QggZuCDMqDhIeiD4AIQjOAB"
    "IIziATig4QIooOEjOI7gAMCg44MwoOEiCFThusCD4QEQgeJCyKDh9P//irTgG+UBMIfiDiig4QM4oOFCaKDhAICg40N4oOEGKKDh"
    "CMCg4ZP//+oNwKDh8N8t6QLgoOGUIZ/lBLBM4pJOjOAc0E3iLEOg4TVAS+WAIZ/lNVBb5QDA0uUAAFXjACCg4zYgS+UzIEvlLyBL"
    "5S4gS+UtIEvlLCBL5SsgS+U3IEvlNCBL5UwhnwUBGKDhA5Cg4UGooOGSHoMAAAig4aMyoAE4wEvlQAig4TDAS+UEYNvlCHDb5QyA"
    "2+U2MEsFBgAACoQyZOADMYTgCBGf5YMxTuCRw4LgoiKg4TYgS+U2wFvlAABc4/AgnwWSHoMAozGgATcwSwUJAAAK2CCf5ZJOg+Cj"
    "MqDhAzGD4AMxg+DIEJ/lAzFO4JFDguCiIaDhNyBL5bQgn+WSToPgozGg4QMxg+CDME7gAABV4zgwS+UE4KATBgAAGgAAXOMD4KAT"
    "AwAAGjcwW+UAAFPjAeCgAwLgoBMAIKDjKBBL4g4wgeAOAFLhAsCg4RAgQ+UKAAAqDjBs4ChAS+IDIITgERBS5QEwjOIMIITg/8AD"
    "4jAQgeIOAFzhCBBC5fT//zoKGKDhAAig4SAIoOEhGKDhMCBL4gkwoOHAAY3o3P7/6/BvG+ke/y/h001iENjOBAgfhetRzczMzDBA"
    "LelQMJ/l/xAB4gDgoOMAUJPlAECg4Q7AoOEBAqDhATCO4iwYoOEDOKDhASCA4EPooOGBEKDhDjig4bQQkeGCIKDhDwhT4wPAoOG1"
    "EILh8v//mjBAvege/y/h5A0AAzBALelQMJ/l/xAB4gDgoOMAUJPlAECg4Q7AoOEBAqDhATCO4iwYoOEDOKDhASCA4EPooOGBEKDh"
    "Djig4bQQkeGCIKDhDwhT4wPAoOG1EILh8v//mjBAvege/y/h6A0AAwTgLeU4MJ/lABCg4wDgk+UBwKDhATCB4gM4oOFDGKDhASig"
    "4aw3oOH/CFLjAsCg4bAgk+G+IIPh9f//mgTgneQe/y/h5A0AAzQwn+UAEKDjAMCT5QEAoOEBMIHiAzig4UMYoOEBKKDhoDeg4f8I"
    "UuMCAKDhACCg47wgg+H1//+aHv8v4eQNAAMBGKDhIRig4QESYeAYMJ/lAAig4QESoOEgGIHgAACT5YEQoOGwIIHhHv8v4cwNAAMw"
    "AJ/lABCg44EhoOGgwKDjARCB4gAwguCwwILhfwBR4wAgoOPwwKDjtCDD4bLAw+H0///aHv8v4YAGAAP/AADi/xAB4gEAUOEE4C3l"
    "CwAAqjDAn+WAIaDhoOCg4wEAgOIMMILgvOCC4QEAUOEAIKDj8OCg47Qgw+Gy4MPh9P//ugTgneQe/y/hgAYAAwLAoOGyMNDhsCDQ"
    "4f48A+L/LALisjDA4bAgwOEE4C3lAABR4wHgoOGwMNDhAuyBsrIQ0OEAAFzjAcyMsg4QgeEMMIPhsDDA4bIQwOEE4J3kHv8v4QIo"
    "oOFwQC3pImig4QDgoOMBGKDhBgBe4QBQoOFBGKDhEQAAKkgwn+UBKKDhAECT5aIFoOEOwKDhATCO4iwYoOEDOKDhASCA4EPooOGB"
    "EKDhDjig4bUQkeGCIKDhIwhW4QPAoOG0EILh8v//inBAvege/y/h8A0AAxBALelEMJ/lAACg43/PoOMA4JPlOECf5QPAjOIAEKDh"
    "ATCA4gM4oOFDCKDhACig4aE3oOEiCFzhAhCg4bQgk+G+IIPh9f//KhBAvege/y/h7A0AA4AGAAMAABDvHv8v4QAAEe8e/y/hAAAS"
    "7x7/L+EAABPvHv8v4QAAFO8e/y/hAAAV7x7/L+EAABbvHv8v4QAAF+8e/y/hAAAY7x7/L+H/EAHiAAig4YESoOEAwN3lIBiB4Awm"
    "guGBEKDhsyCB4R7/L+ENwKDhcNgt6QEzoOMAQKDj7yCg47Alw+EDYKDhBLBM4gBYoOEEMKDhQzyg4bQ1xuEAAKDjJRig4TX9/+sB"
    "IITi/0AC4gQ8oOEPBFPj9f//2nBoG+ke/y/hDcCg4XDYLekBM6DjAECg4+8goOOwJcPhA2Cg4QSwTOIAWKDhBDCg4UM8oOEQMGPi"
    "tDXG4QAAoOMlGKDhHv3/6wEghOL/QALiBDyg4Q8EU+P0///acGgb6R7/L+EAAKDjHv8v4Q3AoOHw2S3pVEGf5QzQTeIEsEziuCDU"
    "4bQw1OG2wNThsgDU4bDg1OGyEFThAsiM4AMIgOAsIZ/lLDGf5Q4YgeAAEIPlAACC5SAxn+UgIZ/lAuyM4gDgg+UAwILlDgEA6xCB"
    "n+VNAADrujDU4bAwyOGwMNjhAABT47RAVAH4IJ/l+DCf5fhwn+UAIIPlsEDIAQDAoOMAMJflDECg4wsAoOMBEKDj3CCf5QTAjeUA"
    "wI3lCECN5ZT9/+uwMNjhCQBT48Rgn5UNMKCTBwAAmgowQ+IDOKDhWQhT46xgn5WwQMaRAgAAmqBgn+ULMKDjsDDG4QBAoOOwANbh"
    "sCDY4QAwl+UMUKDjAhCg4wBAjeUwAI3pOP7/6wAwl+UPAKDjAhCg42ggn+UIUI3lAECN5QRAjeV1/f/rWBCf5Vgwn+VYIJ/lABCD"
    "5QBAwuWwQMbhsEDI4UQEAOu0AgDrMAMA6/gAAOv8///q4u8ECMAKAAPgCgADgAsAA8ALAAOACgADIAsAAwALAAPgCwADyP0ECJAL"
    "AAPU/QQI7u8ECGAGAAPoCgADDcCg4fDdLekC203iBLBM4gTQTeKQMp/lQR+g4wBAk+WBE4HigjCg4wYMoOMpzaDjMe2g4wrAjOIP"
    "4I7iASOg47AwweEFAIDiARug4309oOO4EMLhugDC4bzAwuG+4MLhADCC5UQyn+VEAp/lAECD5QwQoONl/v/rOAKf5Q0QoONi/v/r"
    "MAKf5Q4QoONf/v/rKAKf5Q8QoONc/v/rIAKf5QAQoONZ/v/rKi2g4xQCn+UAEKDjoPv/6wwCn+UBEKDjUv7/6/YuoOMAAp/lARCg"
    "45n7/+vwAZ/lAhCg40v+/+vgIKDj6AGf5QIQoOOS+//r1AGf5QMQoONE/v/r1AGf5QMQoOPgIKDji/v/68hxn+XIgZ/lAGCg4wBA"
    "oOOGUqDhBDCF4IMwoOG3IJPhBACg4QAwmOUBwKDjBhCg4QDAjeUO///rATCE4v9AA+IfAFTj8v//mgEwhuL/YAPiEwBW4+z//5qC"
    "rkviAICg4wSgSuIAAFjjaDGfFWgxnwUAcJMVZEGfFQBwkwVgQZ8FCsCg4QBgoOMAUKDjAOCg44UBoOEAEKDjATCA4AEggeKDMKDh"
    "/xAC4rQwk+EHAFHjsjDM4Pf//5oBMI7i/+AD4gMAXuPy//+aATCF4v9QA+IDAFXj7P//mgEwhuL/YAPiBwBW4+f//5oAYKDjAECg"
    "44ZSoOEEIIXgJBBL4oIwgeACO0PisCDT4QQAoOEHMKDhAsCg4wYQoOEAwI3l1P7/6wEwhOL/QAPiHwBU4/D//5oBMIbi/2AD4h8A"
    "VuPq//+aATCI4v+AA+IBAFjjxP//mkn+/+tMAJ/lABCg4wD+/+uAAJ/lABCg40AgoON6/v/rdDCf5UEuoOMNIILiARmg4xwQgeKw"
    "IMPhACCg47IQw+G0IMPhjv7/6/BtG+ke/y/hXA0AA+ALAAOe5AQIDv0ECC79BAhO/QQIPuUECF7lBAjezgQI/tMECJ7iBAi+4wQI"
    "/s4ECGQNAAN8DQADdA0AA37jBAhe4gQIvuQECIAGAAMNwKDhENgt6QE7oOMBI6DjBDCD4gAwguWAEJ/lBLBM4gAAkeXq/f/rAQCg"
    "453+/+tsMJ/lBhSg4wAAk+WC/v/rEPz/6woAoOOs/v/rAQCg4wAQoOPIIKDjE/z/6zIAoOOQ/v/rAECg4yAQoOP/AATiADCg4wEg"
    "oOEa+//rATCE4gM4oOEfCFPjQ0ig4fX//5r8+//rAQCg4xBoG+mX/v/qwAsAA4ALAAMNwKDhANgt6QSwTOLz+//rPDCf5QAg0+UB"
    "IILiACDD5QAg0+UsEJ/lPwAS4wAw0QUBMIMCADDBBYYAAOs+/v/rFDCf5QAAk+UEAADrAGgb6R7/L+E5DQADOA0AAwALAAPwRy3p"
    "6MGf5QAwnOUAIJPltDHQ4SAAEuMBEMMDAxCgEQAwnOUAoKDhACCT5bYx2uEQABLjsBDK4QEQwwMDEKARADCc5QAgk+W4MdrhQAAS"
    "47IQyuEBEMMDAxCgEQAwnOUAIJPlujHa4YAAEuO0EMrhARDDAwMQoBEAMJzlACCT5bwx2uEBABLjthDK4QEQwwMDEKARADCc5QAg"
    "k+W+MdrhAgAS47gQyuEBEMMDAxCgEQAwnOUAIJPlsDLa4QgAEuO6EMrhARDDAwMQoBEAMJzlACCT5bIy2uEEABLjsBHK4QEQwwMD"
    "EKARADCc5QAgk+WyEcrhtDLa4QIMEuMBEMMDAxCgEQAwnOUAIJPltjLa4QEMEuMBkMMDA5CgEQAwnOW8EMrhABCT5QAAk+UAwJPl"
    "AOCT5QCAk+UAQJPlAFCT5QBgk+UAcJPlACCT5aESoOEgAqDhLMOg4a7joOGkQKDhpVGg4SZhoOGndKDhIiSg4QEQIeIBACDiAcAs"
    "4gHgLuIBgCjiAUAk4gFQJeIBYCbiAXAn4gEgIuIBEAHiAQAA4gHADOIB4A7iAYAI4gFABOIBUAXiAWAG4gFwB+IBIALitiLK4b6Q"
    "yuG0EcrhtgHK4bjByuG64crhvIHK4b5ByuGwUsrhsmLK4bRyyuHwR73oHv8v4dANAAPwwZ/lADDc5QIAU+ME4C3lRwAAiuAxn+UA"
    "MNPlAwAT4zcAABo/MAPiMABT4wPxn5czAADq5MEECLzBBAi8wQQIvMEECLDBBAi8wQQIvMEECLzBBAjcwQQIvMEECLzBBAi8wQQI"
    "1MEECLzBBAi8wQQIvMEECMzBBAi8wQQIvMEECLzBBAjEwQQIvMEECLzBBAi8wQQIvMEECLzBBAi8wQQIvMEECLzBBAi8wQQIvMEE"
    "CLzBBAjMwQQIvMEECLzBBAi8wQQI1MEECLzBBAi8wQQIvMEECNzBBAi8wQQIvMEECLzBBAiwwQQIvMEECOTBBAi8wQQI5MEECCIg"
    "oOMBM6DjTCCD5QTgneQe/y/hqiCg4/n//+qIIKDj9///6mYgoOP1///qRCCg4/P//+oAIKDj8f//6sAwn+UAINPlAQAS4/8QAuII"
    "AAAasDCf5QAg0+UCAFLjATOgAwEzoBO6EcMBvhHDEbgRwwG8EcMRADDc5QYAU+Pi//+aAROg47ww0eEDMMPjvDDB4XDgn+W+INHh"
    "AADe5QMgwuMAMKDjAwBQ4wAwzOW+IMHhCgAACgIAUOPT//8avDDR4QMwg+O8MMHhviDR4QEgguO+IMHhAzCg4wAwzuXK///qvDDR"
    "4QIwg+O8MMHhviDR4QIwoOMDIILjviDB4fX//+o4DQADOQ0AA/wNAAMNwKDh8N8t6Twxn+UEsEzigNBN4gAIoOEAYJPlIAig4QAB"
    "gOAAkKDjAGOG4AmAoOGo4EviKDBL4n/AoOMBwFzigIBD5QEwg+L7//9aAHCg4wMAV+MH8Z+XBAAA6ijDBAjwwwQI+MMECADEBAgA"
    "oKDjAMCg4wFQoOMKQKDhBADW54AgoOMDEKDjAgAQ4QBQzhWiIKDhAgAQ4QAw3hUQMIMTADDOFQEQUeKiIKDhAeCO4vT//1oBwIzi"
    "BwBc4wJAhOLt///aAXCH4gMAV+Pf///aAkCJ4oQYoOEhGKDhqABL4kAgoOPf/P/rCTKg4VzAn+WEAaDhKDCD4kcuoOMBkIniDBCA"
    "4AE5g+MEQaDhCiCC4gkAWeO8IIDhtEDB4bIwweEgYIbiwf//2uz8/+vwbxvpHv8v4QGgoOPM///qEKCg48r//+oRoKDjyP//6sAK"
    "AAOABgADDcCg4fDfLekUMZ/lDNBN4gSwTOIAUNPl/yAA4gVRheCCaKDh/HCf5QIgheD4oJ/lAWeG4oIQoOEmaKDhAECg4/qQkeEA"
    "MJflBhCg4QEgguIGAKDjAECN5QRAjeUIQI3lp/v/68Qwn+UJGKDhACCT5SEYoOG4gJ/lgRFh4AAwl+UBIYLgCgCg4wYQoOEAQI3l"
    "BECN5QhAjeXe+v/rsBDY4QVQgeAFWKDhJVig4YEYoOGFAKDhAReB4vqQkOEAMJflASCF4g5goOMhGKDhBgCg4wBAjeVQAI3pifv/"
    "67AQ2OFIMJ/lCQig4QAgk+WBGKDhIAig4YABYOABF4HiACGC4AAwl+UhGKDhCgCg41AAjekAQI3lv/r/6wUAoOHwbxvpYf//6ugK"
    "AAPgCwAD8AsAA2AGAAOACgADDcCg4fDfLelIIZ/lBLBM4hDQTeIAMNLlPCGf5QMxg+D/kAPisBDS4QUwieIFAKDjAwBR4SwAC+UG"
    "AACqHCGf5ZIBg+AjMaDhAzGD4AEwY+D/MAPiLDAL5QShn+UEQKDjAFCg4wAwmuUEEKDhBQCg4fAgn+UAUI3lBFCN5QhQjeWW+v/r"
    "AjCE4v9AA+IPAFTj8///miwwG+UDAFXhBXCg4SQAACoFgKDhh1ig4QcgieC0AJ/lAVeF4gAAV+OCEKDhJVig4fBAkeEOYKADAGCg"
    "EwAwmuUBIILiBgCg4wUQoOEAgI3lBICN5QhgjeU2+//reDCf5QRIoOEAIJPlJEig4YRBZOAAMJrlCgCg4wQhguAFEKDhCGCN5QCA"
    "jeUEgI3lbvr/6wEwh+IsABvl/3AD4gAAV+Hb//86LDAb5QMwmeEBAAAa8G8b6R7/L+EJAKDh8G8b6Qb//+roCgADoAsAA83MzMzg"
    "CwAD3P0ECPALAANgBgADQROg4wEwoOMAIKDjATCD4gM4oOFVCFPjASDB5EM4oOH5//+aAROg40MvoOOwEIHisDCg4wMgguIAAKDj"
    "ATCD4gM4oOEjCFLhAQDB5EM4oOH5//8qAROg438w4OMAMMHlASCg4QEwoOMhEIHiADDB5TcwwuUnMMLlMTDC5R7/L+ENwKDh8N8t"
    "6ZQzn+UEsEziDNBN4gAQk+WwINHhAABS4wIAABq8wNHhAABc4xAAAApwI5/lADDS5QAAU+MBAAAa8G8b6R7/L+EBMEPiADDC5VQj"
    "n+UAAKDjsADC4Wr//+tIA5/lHBCg4x0goOPwbxvpx/v/6rIw0eEAAFPjAgAAGr4w0eEAAFPjDAAAChTjn+UcM5/lAADe5bAQ0+EA"
    "IYDgBSCC4gIAUeHk///a+DKf5QEggOKwwMPhACDO5eb//+q0wNHhAABc4yUAAArYEp/lsDDR4QAAU+MBMEMSsDDBEQAA0RUBAIAS"
    "GwAAGrQyn+UAINPluDKf5QIhguCwENPhBSCC4gIAUeGcIp+lBDCgo7AwwqEHAACqmCKf5ZIBg+AjMaDhAzGD4AEwY+B4Ep/lATBD"
    "4rAwweEAAKDj5P7/62Qyn+WwINPhYAKf5QIioOEdIILiHBCg48P//+r/AADi9f//6rYA0eEAAFDjJwAACjAyn+UAINPlNDKf5QIh"
    "guCwANPhBSCC4gIAUOELAAC6FAKf5bAw0OEDAFPjATCDkrAwwJEAANCV/BGfhQQAoIOwwMGB4P//igEAQOLm///q8DGf5ZMQguAi"
    "IaDhAiGC4AAAYuDQEZ/lADig4bAg0eEjOKDhATBD4gMAUuG4IZ+lAQBAov8AAKKwwMKhzv//qgEwguKwMMHhAADR5en//+q4MNHh"
    "AABT4wIAABqwMdHhAABT44X//wp4IZ/lADDS5XQhn+WwENLhAzGD4HiBn+UDEIHgsBDI4bAw2OFsEZ/lgzCg4bEgk+FkkZ/lAGCg"
    "4YKhYuAAUKDhPCGf5bAQ0uGwINjhgRig4QEAFuMBF4HiAECgEw1AoAMAMJnlIRig4QEgguIGAKDjAFCN5QRQjeUIQI3lS/r/6/ww"
    "n+UUAZ/lsBDT4QAgkOWBGKDhAReB4gpxoOEAMJnlIRig4QcgguAKAKDjCECN5QBQjeUEUI3lgfn/64YZoOEGF4HiIRig4QUAoOHP"
    "+P/rATCG4v9gA+ICAFbj1///mrAw2OGsEJ/lgzCg4bEgk+GoMJ/liACf5QAQk+WwUMDhgiFi4AIRgeATMNHl/wBT4wQAAAoFEKDh"
    "AQCg47v4/+tXAADrO///6nQwn+UCFKDjAACT5Vf7/+tgEJ/lADCR5QMwh+C4AdPhuiHT4QIUoOO9HIHiAgiA4EAQgeJN+//rBRCg"
    "4QEAoOOo+P/r+f7/6wIEoOMQ/y/hJv//6gALAAPoCgADgAoAA4AGAAOgCwADzczMzJALAAPwCwAD4AsAA2AGAAPgCgADBOAt5VU8"
    "oOMAwKDjAiOg46owg+KwMMLhDhSg4wDAguX/AADisMDC4VUw4ONVIKDjDOCg4QAwweUAIMHlAQDB5QDAweUAwMHlBOCd5B7/L+H/"
    "AADiVSzg4wIToOMAAqDhqiBC4gAwoOOwIMHhADCB5bAAweEe/y/hcEAt6Uwwn+VM4J/lAFCT5QAwoONEYJ/lsDDO4Q5AoOGwANTh"
    "gCFg4AIR1ecAAFHjAcCA4oAgoOEEAAAKsMDE4bAw3uF3AFPjtgCC4fP//5pwQL3oHv8v4WAGAAOgCwAD8AsAAw3AoOHw2S3pRCGf"
    "5bAw0uFAIZ/lgzCg4fIQk+E4cZ/lAYig4ShIoOEAMJflhEFk4ARBoOEDMITgFCDT5RVg0+UDIELiBLBM4gQAoOP/UALis///6wYA"
    "oOHF///rDACg46///+sAMJflA0CE4BMg1OW2MdThAyiC4OAwn+UAAFXjACCD5dgAnwUCO6ADLgAACgEAVePIAJ8FATugAyoAAAoC"
    "AFXjuACfBQY8oAMmAAAKAwBV46gAnwUAMKADIgAACgQAVeOYAJ8VHQAACgcAVuOwMNCRBjKDkbAwwJEAEJflKDig4YMxY+ADEYHg"
    "ECDR5bAw0OEBIILiAjCD4bAwwOG2IdHhXECf5QAAUuMCM6DjADCE5boh0QG4MdEBAjiDAAIzgwIAMIQFaf7/6wAAlOU0MJ/lD+Cg"
    "4RP/L+HwaRvpHv8v4RgAn+UBOqDjsDDA4d3//+qQCwAD8AsAA2AGAAOgCgAD4AwAA2ALAAMQBgADHv8v4QEzoOOCP4PiACCg47AQ"
    "0+EcAJ/lsCDD4RgQn+UBMILiAhGA5/8gA+INAFLj+v//mh7/L+EADQADWM0ECAHDoOMCzIzisCDc4f8AAOIBMKDjEyCC4Wwwn+UC"
    "AFDjsCDM4QARg+cBI6DjBgAAigEAUOMRAAAKCwAAygAAUOO0MNIBCDCDAwUAAAoBI6Djgi+C4rAw0uEBMIPjsDDC4R7/L+G0MMLh"
    "9///6gIAUOP1//8atDDS4SAwg+P4///qtDDS4RAwg+P1///qAA0AAwEToOMCHIHisCDR4f88oOP/AADi/jCD4hMgAuACAFDjsCDB"
    "4QEjoOMGAACKAQBQ4w8AAAoJAADKAABQ47Qw0gEIMMMDAwAACjAgn+UwMJ/lACGD5x7/L+G0MMLh+f//6gIAUOP3//8atDDS4SAw"
    "w+P4///qtDDS4RAww+P1///qWM0ECAANAAMBIELiAQBy4wDAoOEe/y8BATDR5AEgQuIBAHLjATDM5B7/LwH5///qAAAAAAAAH3wA"
    "AP9/10qAAad64mTjDKIANAFZA999HWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQACAAMABAAFAAUABQAFAAUABQAGAAcAAgQBBAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAACAAJAAoACwAMAA0ADgAPABAAEQASABMAEwATABMAEwATABMAEwASBBEEEAQPBA4EDQQMBAsECgQJ"
    "BAgEAAAAABQAFQAWABcAGAAZABoAGwAcAB0AHgAfABMAEwATABMAEwATAB8EHgQdBCAAIQAiACMAJAAlABYEFQQUBAAAAAAmACcA"
    "KAApACoAKwArBCoELAAtAC4ALwAwADEAMgAzADQAMAA1ADYANwArBCoELAAqACsAOAA5ACcEJgQAAAAAOgA7ADwALAgqCCsIKwwq"
    "DCwIKggrCCsMKgwsCCoIKwgrDCoMLAgqCCsIKwwqDCwIKggrCCsMPQA+ADoEAAAAAD8AQABBAEIAQQRDAEMEQQBCAEEEQwBDBEEA"
    "QgBBBEMAQwRBAEIAQQRDAEMEQQBCAEEEQwBDBEEARAA/BAAAAAA/AEUARgBHAEYESABIBEYARwBGBEgASARGAEcARgRIAEgERgBH"
    "AEYESABIBEYARwBGBEgASARGAEkAPwQAAAAAPwBKAEEIQghBDEMIQwxBCEIIQQxDCEMMQQhCCEEMQwhDDEEIQghBDEMIQwxBCEII"
    "QQxDCEMMQQhLAD8EAAAAAD8ATAAqBCwAKgArACsEKgQsACoAKwArBCoELAAqACsAKwQqBCwAKgArACsEKgQsACoAKwArBCoETQA/"
    "BAAAAAA/AE4AKgwsCCoIKwgrDCoMLAgqCCsIKwwqDCwIKggrCCsMKgwsCCoIKwgrDCoMLAgqCCsIKwwqDE8APwQAAAAAPwBQAEEA"
    "QgBBBEMAQwRBAEIAQQRDAEMEQQBCAEEEQwBDBEEAQgBBBEMAQwRBAEIAQQRDAEMEQQBRAD8EAAAAAD8ARQBGAEcARgRIAEgERgBH"
    "AEYESABIBEYARwBGBEgASARGAEcARgRIAEgERgBHAEYESABIBEYASQA/BAAAAAA/AEoAQQhCCEEMQwhDDEEIQghBDEMIQwxBCEII"
    "QQxDCEMMQQhCCEEMQwhDDEEIQghBDEMIQwxBCEsAPwQAAAAAPwBSAFMAVABTBFUAVQRTAFQAUwRVAFUEUwBUAFMEVQBVBFMAVABT"
    "BFUAVQRTAFQAUwRVAFUEUwBWAD8EAAAAAFcAWABZAFkAWQBaAFoAWgBbAFkAWQBZAFoAWgBbBFoEWgRaBFkEWQRZBFsEWgRaBFoE"
    "WQRZBFkEWARXBAAAAABcAF0AXgBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBeBF0EXAQA"
    "AAAAYABhAGIAYwBkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGMEYgRhBGAEAAAAAGUAZgBnAGgA"
    "aQBqAGoAagBqAGoAagBqAGoAagBqBGoEagRqBGoEagRqBGoEagRqBGoEaQRoBGcEZgRlBAAAAABrAGwAbQBuAG8AcABwAHAAcQBx"
    "AHEAcgBwAHAAcQRwBHAEcARyBHEEcQRxBHAEcARwBG8EbgRtBGwEawQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAQAAAQgQARERgAAAAAAAAAEQAAEYUAEYV4EYV4V4V4V4d3JYURUocRoRERERF1V1qqh5WalxWIhYEYoain"
    "cRkRERmRERERmCFhERERESIqqqKampeagoKBgqiop6gRERERZmZmZlZVVVURERERKiqqopeal5qBgoGCp6inqBERERFmZmZmVVVV"
    "VREREREqKqoil5qXmoGCgYKnqKeoEREREWZmZmZVVVVlERERESqqdVeap1l4glGIUaiHGoEREZEXEREZkRYSiREAAAAAAAAAAAAA"
    "AAAAAAARAAAQqQAAoWYAEGlWABBqJQAAAAAAAAAAAAAAAAEAEREZESoapigZKWY5GJhlEooRAAAAAAAAAAAAAAAAAAAAABEREREX"
    "lxkXeqgSKYKKKXoAAAAAAAAAAAAAAAAAEREREaGioil6qXl6ESgYGHiKegAAAAAAAAAAAAAAABERERGioiIqqXmZmigYiIKKeqqo"
    "AAAAAAAAAAAAAAAAEREREaqiKiqXmpeagYKBgqeop6gAAAAAAAAAAAAAAAARERERqqIqmpealyeBgoGap6inEgAAAAAAAAAQAAAQ"
    "IRERIaoqeqKJGamTmHiYihqHGqKnEamih6kqqqKaoniXGZKHgYGSqqiBGnqhp6EREqJ6KqkRcap5iaF1GiNzFxI3inV6eKJ4p1kp"
    "gpGCmCqiqqJadZGZEWGYGWFmmRlmVpkSZlWXGWZVhRFmVakaZlWHEWZVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUA"
    "EGlWAAChZgAAgSkAACETABCaqAAQEoEAEJoYABAhGWaJJ4GmOal4mamKijgqhhqXapaioogZmYiqkpJ4gZqZWlinhih3KRiHI4IR"
    "GJEYEYkoEYGRGnglqRFXd6mBd4hxVVKlEXh1VxGBhYcRWBiBV3KBV3UXeIWIVxeIdReIhCWlVVVXN3d3V5iIeIWBEYGBiIiIiHiI"
    "iIh4iIiISIiIWlVaVXN3c3eJeIl4GIEYgYiISIiHiHiIh4h4iISISIhaVVpac3dzN4l4iZcYgRiBiISISIiHiHiIh4h4iISISCVX"
    "haKneTkieCqiGIGBGIGIiIQYiIiHiIiIh4iIiISIGZKHgZqieJepKqqiF6mih3ERERh4eBGBeIh3F0iIiHc3inV6I3MXEomhdRoR"
    "cap5UocRoXclhRGFeFeHEYV4V5kSZlWZGWZVmBlmVZEZZlURGGFWGZERYXGZIWEYkRERVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
    "VVVVVVZVVVUYeCmReYcqqSqqopp4KppxgRERFxgRh3hxd4h4d4SISCpYdVIik5d6gSqihxiBGBiBiIiIiIiHiIiIh4iIiISIpaVV"
    "pXM3dzd5mIeYGIEYgYiIiIR4iIiHeIiIh0iIiIRVpVWldzd3N4eYh5gYgRiBiIiIiIh4iIiIeIiIiEiIiFVVWlJ3d3N1h4iJdRgR"
    "GFiIiIgYh4h4iIeIeIiEiEiIWiVVF3VXhxF4WBgRGIGFEXUYJ3VYh3FXiHF1iIiIcVcAAHEqAAARhwAAcagAAJGKAACRkgAAcSEA"
    "ABGpAABxcooXGZklGJiqeBOoEXWSEoGXgoF3KhhxdYYRUYcYESiHkRqIdZmZgReaknGBkRmIiBgRhIiBgUR3dYGEiBeIh4gXiEdE"
    "iIiIhHiIiId4iIiHSIiIhER0R0RIiIiEeIiIh3dEdEeISIiIiHiIiIh4iIiISIiId0R0R4hIiIiIeIiIRHdEdISISIiHiHiIh4h4"
    "iISISIhEd0R0hIhIiIeIeIhEdEdESIiIhHiIiId4iIiHSIiIhER0R0RIiIiEeIiIh3cRhXiIdxGFiHh3EYh4iHeISIiId0R0R4hI"
    "iIiIeIiIFRgREYelqKd1h4WBEZWal4hRWqpEGBERhIiIiIeIeIgRERERqKinqIKCgYKampeaIiqqohERERGIiIiIiIeIeBERERGn"
    "qKeogYKBgpeal5oqKqqiEREREYiIiIiIiIeIEREREaeop6iBgoGCl5qXmioqqqIRERERiIiIiHiIiIcRERERp6inqIGCgYKXmpea"
    "KiqqohERERGIiIiIiHiIiBERERGnqKeogYKBgpeal5oqKqqiEREREYiIiIiHiHiIEREREaeop6iBgoGCl5qXmioqqqIRERERiIiI"
    "iIiHiHgRERERp6inqIGCgYKXmpeaKiqqIhERERGIiIiIeIiIhxERgVGoh1p4glF4V5qnWREqqhWIERGBR4iIiIiIeIiIh1gRd1gR"
    "d4gRd3iId4h4iISISIhEd0R0hIhIiIeIeIhHRIhxiISIiIiHiHiIh4h4iISISEdEd0SIhIhIiIeIeFeIoRlxGJmZGBcpqYiIkRmI"
    "iBGBdEcYGIiIFFeIiIdxAACRigAAIRcAAKiBABB6cQAQenEAEJKoABCqggAQkqgREVdYFxF1eIWBcnd1WBcVUoWBF3UYeIF1EVdB"
    "WogVSBeIh4iBiISIcUdEd4iIhIiIiIeIiIiHiIiIhIh0R0R3iIiHcYiIhBh0R0QXiIiEiIiIh4iIiIeIiIiEiHRHRHeFdRERh1cR"
    "cXcnGFhRcYVXcRhYJRiHgVcYdRFXhFGIpQAQenEAEJKoABCqggAQkqgAEHJxABCaqAAQooIAEJKodVcXSFKFgXh1EYF4dRiISDoZ"
    "eER1EYhIdYGIeHUYiHiIiISIiIiHiIiIh4iIiISIdEdEd4iIhIiIiIeIiIiHiEiIiIR4iIiHeIiIh0iIiIREdEdESIiIhHiIiId4"
    "iIiHhIhIiIeIeIiHiHiIhIhIiER3RHSEiEiIh4h4iIeIeIhIcXVXeBhYJXgYEVdIiIFXRISRo0iIEVd4iBhXeIiBVzoZiEh1EXhE"
    "dYGISHUYiHg6GYh4dRGISHWBeER1GIhIiIiEiHRHRHeIiISIiIiHiIiIh4iIiISIdEdEd4iIhIhIiIiERHRHREiIiIR4iIiHeIiI"
    "h0iIiIREdEdESIiIhISISIhEd0R0hIhIiIeIeIiHiHiIhIhIiER3RHSEiEiISIiRo0SEEVdIiBhXeIiBV3iIkaNIiBFXRIQYV0iI"
    "gVc6GYh4dRGIeHWBiEh1GHhEOhmISHURiHh1gYh4dRiISHiIkaN4iBFXSIgYV0SEgVdIiJGjeIgRV3iIGFdIiIFXOhl4RHURiEh1"
    "gYh4dRiIeDoZiEh1EXhEdYGISHUYiHhEhJGjSIgRV3iIGFd4iIFXSIiRo0SEEVdIiBhXeIiBVzoZiHh1EYhIdYF4RHUYiEg6GYh4"
    "dRGIeHWBiEh1GHhEeIiRo0iIEVdEhBhXSIiBV3iIkaN4iBFXSIgYV0SEgVc6GYhIdRGIeHWBiHh1GIhIOhl4RHURiEh1gYh4dRiI"
    "eEiIkaN4iBFXeIgYV0iIgVdEhJGjSIgRV3iIGFd4iIFXOhl4RHURiEh1gYh4dRiIeDoZiEh1EXhEdRGBSHWYERF0R0R3iIiEiIiI"
    "h4iIiIeIiIiEiHRHRHeIiISIEREREUR0R0RIiIiEeIiIh3iIiIdIiIiERHRHREiIiIQRERERRHdEdISISIiHiHiIh4h4iISISIhE"
    "d0R0hIhIiBERERFEhJGjSIgRV3iIGFd4iIFXSIiRo0SEEVdIGBFXERGJVwAQenEAEJKoABCqggAQkqgAEHJxABCSqAAQqoIAEJKo"
    "OhkqKnURmJpVgYeCdVinqDoZVVV1GHV3dVGBeFKFGIGqoioql5qXmoGCgYKnqKeoWlVaVXN3c3eJeIl4GIEYgSoqqqKXmpeagYKB"
    "gqeop6haVVpVc3dzd4l4iXgYgRiBKioqKpeal5qBgoGCp6inqFpVWlVzd3N3iXiJeBiBGIEAEHpxABCSqAAQqoIAEJKoABB6cQAQ"
    "enEAAKiBAAAhF3VXF4FaiBUYdRFXEXUYeIFShYEXdVgXFYWBcncXEXV4GIEYgREREREREREREREREREREREYEREREREREYEREREY"
    "gRiBEREREREREREREREREREREREREREREREREREREQAAkYoAAHFyAAARqQAAcSEAAJGSAACRigAAcagAABGHERFXWBgRKIeGEVGH"
    "KhhxdZeCgXd1khKBeBOoESUYmKoXERERFxgREXURERGBgRERGBEREZEZiBGaknGBmZmBFxERERERERERERERERERERERERERERER"
    "ERERERGIEREREREREREREREREREREREREREREREREREREREREREREREAAHEqABAhGQAQmhgAEBKBABCaqAAAIRMAAIEpAAChZooX"
    "GZl4gZqZiKqSkqKIGZmXapaiOCqGGpmpioqmOal4kRqIdamBd4ipEVd3kRp4JYkoEYEYkRgRhyOCESh3KRgXiBERdReIEYhXF4h1"
    "F3iFV3KBVxFYGIERgYWHEXh1VxEREREREREREREREYgRERGBiBERhYERgVeYiHhXN3d3EREREREREREREREREREREREREREYgRiB"
    "iXiJeHN3c3cAEGlWABBqJQAQaVYAAKFmAAAQqQAAABEAAAAAAAAAAGaJJ4FlEooRZjkYmKYoGSkZESoaAQAREQAAAAAAAAAAWlin"
    "hoKKKXp6qBIpF5cZFxEREREAAAAAAAAAAAAAAABxVVKlGHiKenoRKBgpeql5EaGiogAREREAAAAAAAAAACWlVVWKeqqoKBiIgql5"
    "mZqioiIqEREREQAAAAAAAAAAWlVaVaeop6iBgoGCl5qXmqqiKioRERERAAAAAAAAAABaVVpVp6inqIGCgYKXmpeaKiqqohEREREA"
    "AAAAAAAAAFpVWlWnqKeogYKBgpeal5oqKioqEREREQAAAAAAAAAAAAABAAEEAAAAAAEAAQQAAAIAAwADBAIEAgADAAMEAgQEAAUA"
    "BQQEBAQABQAFBAQEAAAGAAYEAAAAAAYABgQAALu7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7y7u7u8y7u8vMu7vM"
    "zLvLzMy7zLu7y7vMzLzLzMy7u7vLu7u7zLu7y7y7u8y8u8vMvLvMzMvLzMzLzMzMy8u7zMzLu7u7zLvMvMzLu8vMy8vLzMu7y8zL"
    "u7zMy8y8zMzMy8vMzMu7zMy8u8vMvLu7zLy7u8vMu7u7zLu7u8vMu8zMzLu7u8y7u7vMy7u8zLvMy8u8u7vLzLu8vMy8u8y7zMzL"
    "zLu7u8zMzLvLzMy7u8zMu7vLzLu7u8y7u7vLAAABAAEEAAAAAAEAAQQAAAIAAwADBAIEAgADAAMEAgQEAAUABQQEBAQABQAFBAQE"
    "AAAGAAYEAAAAAAYABgQAAMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMvMzMzLvMzLy7zMy7u8y8u7vMu8zMvMy7"
    "u8u8u7vMzMy8zMzMu8zMvMvMzLvLzLy7y8y7u7y8u7u8u7u7vLzMu7u8zMzMu8y7y7u8zLy7vLy8u7zMvLu8zMu7vLvLu7u7vLy7"
    "u7zMu7vLzLy7y8zMu8vMzLy7zMzMu8zMzLy7zLu7u8zMzLvMzMy7vMzLu8y7vLzLzMy8u8zLy7vLzLvMu7u8u8zMzLu7u8y8u7vM"
    "zLu7zMy8u8zMzLvMzMy8H3z/fwAA330dYDQBWQMAAAAAAAAAAAAAAAAAAAAAAAAAISIBECImERBSJiEhJSUiIVJiQiEiUjJSJmUl"
    "IiIlZQAAAAARAQAAIhIBAEQkEgBEMyQBMxMhAUQTQRJCNEMSUiZWZiIiJSUhUlJCISViQiEiJSIQUiYhECImEQAhIgFCNEQSRDRE"
    "EkQ0JAFEQyQBMyQSACISAQARAQAAAAAAAB98AAD/fwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAIiIAIAIgAiACIAIgIiICIAIgAiACIAIgAiACAAAAACAiIgAgAiACIAIgAiAiIgAgAiACIAIgAiAiIgAA"
    "AAAAACAiAgAiAAAgAgAAIAIAACACAAAAIgAAACAiAgAAAAAgIgIAIAIiACACIAIgAiACIAIgAiACIgAgIgIAAAAAACAiIgIgAgAA"
    "IAIAACAiAgAgAgAAIAIAACAiIgIAAAAAICIiAiACAAAgAgAAICICACACAAAgAgAAIAIAAAAAAAAAIiIAIAIgAiACAAAgAiICIAIg"
    "AiACIAIAIiICAAAAACACIAIgAiACIAIgAiAiIgIgAiACIAIgAiACIAIAAAAAACIiAAAgAgAAIAIAACACAAAgAgAAIAIAACIiAAAA"
    "AAAAACACAAAgAgAAIAIAACACAAAgAiACIAIAIiIAAAAAACIAIAIiACIAIiACACIiAAAiIAIAIgAiACIAIAIAAAAAIAIAACACAAAg"
    "AgAAIAIAACACAAAgAgAAICIiAgAAAAAiACACIgIiAiIiIgIiICACIgAgAiIAIAIiACACAAAAACIAIAIiAiACIiIgAiIgIgIiACIC"
    "IgAgAiIAIAIAAAAAACIiACACIAIgAiACIAIgAiACIAIgAiACACIiAAAAAAAgIiIAIAIgAiACIAIgIiIAIAIAACACAAAgAgAAAAAA"
    "ACAiAgAiACIAIgAiACIAIgAiIiIAIiAiACAiIAIAAAAAICIiACACIAIgAiACICIiACACIgAgAiACIAIgAgAAAAAAIiIAIAIgAiAi"
    "AAAAIiIAAAAiAiACIAIAIiIAAAAAACAiIgIAIAIAACACAAAgAgAAIAIAACACAAAgAgAAAAAAIAIgAiACIAIgAiACIAIgAiACIAIg"
    "AiACACIiAAAAAAAgAiACIAIgAiACIAIgAiACACIiAAAiIgAAIAIAAAAAACIAIAIiACACIgAgAiIgIAIiIiICIgIiAiIAIAIAAAAA"
    "IgAAIiACIAIAIiIAACACAAAiIgAgAiACIgAAIgAAAAAiAAAiIAIgAgAiIgAAIAIAACACAAAgAgAAIAIAAAAAACIiIgIAACIAACAC"
    "AAAiAAAgAgAAIgAAACIiIgIAAAAAAAAAAAAAAAAAIiIAAAAgAgAiIgIgAiACACIiAgAAAAAgAgAAIAIAACAiIgAgAiACIAIgAiAC"
    "IAIgIiIAAAAAAAAAAAAAAAAAACIiACACAAAgAgAAIAIAAAAiIgAAAAAAAAAgAgAAIAIAIiICIAIgAiACIAIgAiACACIiAgAAAAAA"
    "AAAAAAAAAAAiIgAgAiACICIiAiACAAAAIiIAAAAAAAAgIgAAIgAAICIiAAAiAAAAIgAAACIAAAAiAAAAAAAAAAAAAAAAAAAAIiIC"
    "IAIgAiACIAIAIiICAAAgAgAiIgAgAgAAIAIAACAiIgAgAiACIAIgAiACIAIgAiACAAAAAAAgAgAAAAAAACACAAAgAgAAIAIAACAC"
    "AAAAIgAAAAAAAAAiAAAAAAAAACIAAAAiAAAAIgAAACIAAAAiACAiAgAgAgAAIAIAACACIAIgAiIAICICACACIgAgAiACAAAAAAAg"
    "AgAAIAIAACACAAAgAgAAIAIAACACAAAgAgAAAAAAAAAAAAAAAAAiAiIAIiIiAiIgIAIiACACIgAgAgAAAAAAAAAAAAAAACAiIgAg"
    "AiACIAIgAiACIAIgAiACAAAAAAAAAAAAAAAAACIiACACIAIgAiACIAIgAgAiIgAAAAAAAAAAAAAAAAAgIiIAIAIgAiACIAIgIiIA"
    "IAIAACACAAAAAAAAAAAAAAAiIgIgAiACIAIgAgAiIgIAACACAAAgAgAAAAAAAAAAIAIiACAiIAIgAgAAIAIAACACAAAAAAAAAAAA"
    "AAAAAAAAIiIAIAIAAAAiIgAAACACICIiAAAAAAAAIgAAACIAACAiIgAAIgAAACIAAAAiAAAAICIAAAAAAAAAAAAAAAAAIAIgAiAC"
    "IAIgAiACIAIgAgAiIgIAAAAAAAAAAAAAAAAgAiACIAIgAiACIAIAIiIAACACAAAAAAAAAAAAAAAAACIAIAIiACACIiAgAiIiIgIg"
    "AiIAAAAAAAAAAAAAAAAAIgAgAiACIgAAIgIAIAIiACIAIAIAAAAAAAAAAAAAAAAgAiACIAIgAiACIAIAIiIAACACAAAiAAAAAAAA"
    "AAAAACAiIgIAACIAACACAAAiAAAgIiICAAAAAAAiIgAgAiACIAIiAiAiIgIgIiACIAIgAgAiIgAAAAAAACACAAAiAgAgIgIAACAC"
    "AAAgAgAAIAIAACACAAAAAAAAIiIAIAIgAgAAIAIAACIAACACAAAiAAAgIiICAAAAAAAiIgAgAiACAAAgAgAgIgAAACACIAIgAgAi"
    "IgAAAAAAACAiAAAiIgAgAiIAIgAiACIiIgIAACIAAAAiAAAAAAAgIiICIAIAACAiIgAAACACAAAgAiACIAIAIiIAAAAAAAAgIgAA"
    "IgAAIAIAACAiIgAgAiACIAIgAgAiIgAAAAAAICIiAgAAIAIAACACAAAiAAAgAgAAIAIAACACAAAAAAAAIiIAIAIgAiACIAIAIiIA"
    "IAIgAiACIAIAIiIAAAAAAAAiIgAgAiACIAIgAgAiIgIAACACAAAiAAAiAgAAAAAAACACAAAgAgAAIAIAACACAAAgAgAAAAAAACAC"
    "AAAAAAAgAiIAIAIiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACACIgAgAiIAIiIiAiACIgAiIiICIAIiACACIgAAAAAAACACAAAi"
    "IgIgAgAAACIiAAAAIAIgIiIAACACAAAAAAAAAAAAIAIgAgICIgAiIAIAACIgAiACAgIiACIAAAAAAAAiAgAgAiIAIAICACAiIAIi"
    "ICIAIgAiAiAiAiIAAAAAACACAAAgAgAAIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAACACAAAiAAAAIgAAACIAAAAgAgAAACIA"
    "AAAAAAAiAAAAIAIAAAAiAAAAIgAAACIAACACAAAiAAAAAAAAAAAAACACIAIAIiIAIiIiIgAiIgAgAiACAAAAAAAAAAAAAAAAACAC"
    "AAAgAgAgIiICACACAAAgAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACACAAAgAgAAIgAAAAAAAAAAAAAAAAAAICIiAgAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAgAAIAIAAAAAAAAAACIAACACAAAiAAAgAgAAIgAAIAIAACIAAAAA"
    "AAAAAAAAAAAgAgAAIAIAAAAAAAAAAAAAIAIAACACAAAAAAAAAAAAACACAAAgAgAAAAAAAAAAAAAgAgAAIAIAACIAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAACAiIgIAAAAAAAAAAAAAAAAgIiICAAAAACAiIgIAAAAAAAAAAAAAAAAAAAAAIAIAAAAgAgAAACACACAC"
    "ACACAAAAAAAAAAAAAAAiIgAgAiACAAAgAgAAIgAAIAIAAAAAAAAgAgAAAAAAAwAmFQUIJhUFCAwABQgDAEdCQS1Ob3RlcGFkAAAA"
    "AAAAAAAHAwAAAMAAAABwaWFubwAAAAAAAAAAAAAAAAAACQMAgAEAAAMAQmlvc19EdW1wZXIAAAAAAAAAAAkDAAACAAAEAAAgICAg"
    "ICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAA"
    "AAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAg"
    "IAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAg"
    "ICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAA"
    "AAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAg"
    "AAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAg"
    "ICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAA"
    "AAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAA"
    "AAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAg"
    "ICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAA"
    "AAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAA"
    "AAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAg"
    "ICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAA"
    "ACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAA"
    "AAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAg"
    "ICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAA"
    "ICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAA"
    "AAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAg"
    "ICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAg"
    "ICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAA"
    "AAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAg"
    "ICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAg"
    "ICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAA"
    "AAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAg"
    "ICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAg"
    "ICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAA"
    "AAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAg"
    "ICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAg"
    "ICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAA"
    "AAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAg"
    "IAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAg"
    "ICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAA"
    "AAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAg"
    "AAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAg"
    "ICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAA"
    "AAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAA"
    "AAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAg"
    "ICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAA"
    "AAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAA"
    "AAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAg"
    "ICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAA"
    "ACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgAAAA"
    "AAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAICAgICAgICAg"
    "ICAgICAgAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAB98AAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAH3wAAOF/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAffAAAtDMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEFCQ0RF"
    "RkdISUpLTE1OT1BRUlNUVVZXWFlaYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU2Nzg5ISAjJCUmICgpKissLS4vOjtf"
    "PT4/AAAAAEdCQSBNZW51AAAAAGluIDEAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAA//8BI6DjADKy5bgQ0uEAAE/h"
    "B0At6QEAoOO4AMLhIxgD4OTAn+UBABHiJQAAGgTAjOICABHiIgAAGgTAjOIEABHiHwAAGgTAjOIIABHiHAAAGgTAjOIQABHiGQAA"
    "GgTAjOIgABHiFgAAGgTAjOJAABHiEwAAGgTAjOKAABHiEAAAGgTAjOIBDBHiDQAAGgTAjOICDBHiCgAAGgTAjOIBCxHiBwAAGgTA"
    "jOICCxHiBAAAGgTAjOIBChHiAQAAGgTAjOICChHisgDC4QAwD+HfMMPjHzCD4wPwKeEAAJzlAEAt6QDgj+IQ/y/hAEC96AAwD+Hf"
    "MMPjkjCD4wPwKeEHQL3ouBDC4QDwaeEe/y/hAA0AA1U84OMCE6DjqjBD4rAwweEcIJ/lHDCf5QDAkuWwINPhAMCB5bAgweEAMKDh"
    "APCg4R7/L+GgCgAD4AwAAwAAAAYAQAAGAIAABgDAAAYAAAAGAAgABgAQAAYAGAAGACAABgAoAAYAMAAGADgABgBAAAYASAAGAFAA"
    "BgBYAAYAYAAGAGgABgBwAAYAeAAGAIAABgCIAAYAkAAGAJgABgCgAAYAqAAGALAABgC4AAYAwAAGAMgABgDQAAYA2AAGAOAABgDo"
    "AAYA8AAGAPgABgAAAAYwAQAEAEAABgBgAAYAgAAGAKAABgDAAAYA4AAGAAABBgAgAQYAQAEGgAYAAwIAAAAAAMADHgAAeAAhAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAlgAfBAQEAAIwBZAL8BHwEf/wEfAR8BHw"
    "EfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR"
    "8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR"
    "8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHw"
    "EfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/w"
    "EfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR"
    "8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHw"
    "Ef/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHw"
    "EfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR"
    "8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR"
    "8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHw"
    "EfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR"
    "//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR"
    "8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHw"
    "EfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHw"
    "EfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR"
    "8BHwEcAOFwMDAwACA/AY8BHwEf/wEfAR8BHwEfARoJxABiCk/8AR8CHQQfAS8CjwefAR8BH/8FdQhIAK8JrwOfCbMAowBf+wGeAh"
    "0D/wVPB98CPwEfAR//BXYFmACvDt8Dnwm1Gp0O7/8CHxLvAU8BTwefAR8BHwWf9QWIAK8G7wOfBCAAogBPH3/8Ah8NrwFPB/8Hnw"
    "EfAR8Fn/8OTwb/A48EGw0fDu8DogLf/wHfAx8DfwEfAR8BHw4/Bu//A08ELxupG28CHw77A3g/j/s+J0ErAecEHQeMGM8JXw7//w"
    "pfBCw5qgaPAhkgzQrXA9/6U/4B7F/vUxIG/AyvDk8O//8OLw7/DuwXLw7lHwwZCyEP+w7/AesgeBD1AM8O/w5PDv//Dl9tLSlKHe"
    "8lmE3+Po1dj/8t6198AYYSXgysRU9Grw3//w77d08EDAIZiY5q3AEbHY//Ae8OdgLfCX8dPwFfDf8O//kLvw7tAh+Yj3pvARoprx"
    "/v/0t6Hk8O/w7/DZ8BHwzeUh//Dv0d7wx/DYsEfwL/Dv+4T/8OTw7/De8O6gZOR/8x3XqP/wr/Dv8O/wL/Dv99bzs/KO//Co8THw"
    "3no98E3w7/C397j/8B7bnqJXsSvx0/He8KHwEf+gLPDu8O/w7rDI126GyfAe/9yOp+jzaPDk8O/wp/IhgN7/+VbyLe0W9L+tWbJ4"
    "uGi2/v/+lfY28s7woPCt/vzO5d77//A40OP1cPQe947wvPp8/vv//vvw8fDt8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR"
    "8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHw"
    "EfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEZAL"
    "FwEBAQACAfAY8BHwEf/wEfAR8BHwEfARoJxABiCk/8AR8CHQQfAS8CjwefAR8BH/8FdQhIAK8JrwOfCbMAowBfSwGeAh0D/gUwAQ"
    "MQAA//Bs8BHwEfAR0PCACtAV8DLf8EMgmwAAAiAHEa9ADUAY/+Ah4IHQ2UA68GvwEfAR8BH/8KwQW4AKgArwMvBCYJsw7/8Q7mCz"
    "cE5wIfDa8FLgKPB4//AR8BHwrGBZgArwb/A58EH/EogQ7hAF8O5wIaA9kQzwU//wbvAR8BHwEfBY8O7wbvA//5AsIwAgNLDu8CHw"
    "72AUdOL/Qwez4nQSQAxQFPRO85fw5P/w7/Df8O8wr3BYwO7wIZDu/7DvhOBEAFU/0B5mtaVbpTH/UDvwrNOG8mLw58BCEFaxpf9j"
    "//AhgO6jwBCcROlzCXAh/4AeczNQYGDuMB9ALcQd8OT/8O/w4vXhYIKAE5Du0CFw7/9FvaJtsO9QD+AeVrVmvUAY/2IdAG/zLUAO"
    "gAr2DfDm0xH/8FZjEMAhmJhi+2B4tc+AyP8w5/AecQCQDmIjs5nzs/O+//Di8O8QWHAxss3AIfmI4L7/8O8ACNLlgB7iFnMToIjw"
    "5P/w7/Dg8O8xgqDfZZrgIWDg/za5sNSilpCIcqbwHtHmcO//M86AyfOz877w4vguZoXQ7v9VXWAhMIw5a1ALhI7w0FE3//Dv4OfV"
    "6SAM0O7zs/O+8Ob/9tA0efDucobA71HedV7gt/9x+WTX8B5wr5GyiiK3m/LD//LO8ObwQrHNUI9hlvBOdp3/kK9mfmTaR7hmltPv"
    "0BCYjf9TUvCs8O/w2/ARogtn/KlW//Ith2rLQu44cApwHqhohBL/ve4yV1AL8s7yzvDc8BHO2v/ADgBG/lrZ6e85aGaaHYGJ/7Al"
    "gheQV3IeYO7+8P778OH//qqF7ygEsA80MfE+QC3QRP9Uy0PicBCAJ0BjQAeQF4A//5BM8Kywt/Cg8KyQQLCkwLL/oIHgOaBDcSJw"
    "ycCMsB6w7//QV/A8cGiACvCg8ObwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR"
    "//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR"
    "8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BHg8BHwEfARBAQCAgK/AAIC8BjwEfAR8BHwEfAR//AR"
    "8BGgnEAGIKTAEfAh0EH/8BLwKPB58BHwEfBXUISACv/wmvA58JswCjAFsBngIdA///BU8H3wI/AR8BHwV2BZgAr/8O3wOfCbUanQ"
    "7vAh8S7wFP/wFPB58BHwEfBZUFiACvBu//A58EIACiAE8ffAIfDa8BT/8H/wefAR8BHwWfDk8G/wOP/wQbDR8O7wOiAt8B3wMfA3"
    "//AR8BHwEfDj8G7wNPBC8br/kbbwIfDvsDeD+LPidBKwHv9wQdB4wYzwlfDv8KXwQsOa/6Bo8CGSDNCtcD2lP+Aexf7/9TEgb8DK"
    "8OTw7/Di8O/w7v/BcvDuUfDBkLIQsO/wHrIH/4EPUAzw7/Dk8O/w5fbS0pT/od7yWYTf4+jV2PLetffAGP9hJeDKxFT0avDf8O+3"
    "dPBA/8AhmJjmrcARsdjwHvDnYC3/8Jfx0/AV8N/w75C78O7QIf/5iPem8BGimvH+9Leh5PDv//Dv8NnwEfDN5SHw79He8Mf/8Niw"
    "R/Av8O/7hPDk8O/w3v/w7qBk5H/zHdeo8K/w7/Dv//Av8O/31vOz8o7wqPEx8N7/ej3wTfDv8Lf3uPAe256iV/+xK/HT8d7wofAR"
    "oCzw7vDv//DusMjXbobJ8B7cjqfo82j/8OTw7/Cn8iGA3vlW8i3tFv/0v61Zsni4aLb+/pX2NvLO//Cg8K3+/M7l3vvwONDj9XD/"
    "9B73jvC8+nz++/778PHw7f/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHw"
    "EfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR"
    "8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR"
    "8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHw"
    "EfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/w"
    "EfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR"
    "8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHw"
    "Ef/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHw"
    "EfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR"
    "8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR"
    "8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHw"
    "EfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR"
    "//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR"
    "8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHw"
    "EfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHw"
    "EfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR"
    "8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/"
    "8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHw"
    "EfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR"
    "8BH/8BHwEfAR8BHwEfAR8BHwEf/wEfAR8BHwEfAR8BHwEfAR//AR8BHwEfAR8BHwEfAR8BH48BHwEfAR8BGgDAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////////////";


static size_t meaningful_rom_end(const std::vector<uint8_t>& rom)
{
    // writeonerom8MB.pcap proves that Windows can place the single-ROM loader
    // *inside* a power-of-two ROM file's trailing FF padding rather than after
    // the physical file size.  For that capture the loader begins at 0x2CC420
    // even though the programmed image is a full 8 MiB.
    //
    // Use the final non-FF byte as the meaningful data extent.  Keep at least
    // the GBA header/entry area even for pathological files.
    size_t end = rom.size();
    while (end > 0xC0 && rom[end - 1] == 0xFF)
        --end;
    return end;
}


static uint32_t next_power_of_two_u32(uint32_t x)
{
    if (x <= 1u) return 1u;
    --x;
    x |= x >> 1;
    x |= x >> 2;
    x |= x >> 4;
    x |= x >> 8;
    x |= x >> 16;
    return x + 1u;
}

static uint32_t multi_rom_size_class_alignment(size_t file_size)
{
    // The two new original-manager captures are consistent with a buddy-like
    // size-class allocator: an 8-MiB ROM is placed on an 8-MiB boundary, while
    // the 64-KiB Piano image is placed on a 64-KiB boundary. Use the next
    // power-of-two size class for non-power-of-two input files, with 64 KiB as
    // the minimum capture/program granularity.
    if (file_size > MAX_CARD_IMAGE)
        throw std::runtime_error("ROM file exceeds 256-Mbit cartridge capacity");

    uint32_t wanted = static_cast<uint32_t>(
        std::max<size_t>(PROGRAM_BLOCK, file_size));
    const uint32_t a = next_power_of_two_u32(wanted);
    if (a == 0 || a > MAX_CARD_IMAGE)
        throw std::runtime_error("ROM size class exceeds cartridge geometry");
    return a;
}

static uint64_t align_up_u64(uint64_t x, uint64_t a)
{
    return (x + a - 1u) & ~(a - 1u);
}

static std::optional<uint32_t> find_ff_slot_in_image(
    const std::vector<uint8_t>& image,
    size_t required_size)
{
    size_t i = 0xC0;
    const size_t limit = std::min(image.size(), MAX_CARD_IMAGE);

    while (i < limit) {
        while (i < limit && image[i] != 0xFF)
            ++i;
        const size_t run_start = i;
        while (i < limit && image[i] == 0xFF)
            ++i;
        const size_t run_end = i;
        if (run_end <= run_start)
            continue;

        const size_t aligned = (run_start + 15u) & ~static_cast<size_t>(15u);
        if (aligned <= run_end && required_size <= run_end - aligned)
            return static_cast<uint32_t>(aligned);
    }
    return std::nullopt;
}

static std::optional<uint32_t> find_internal_ff_loader_slot(
    const std::vector<uint8_t>& rom,
    size_t required_size)
{
    // writerom128Mb.pcap contains FFTA_INTER. (AFXP) and proves how the
    // original manager handles a ROM whose physical file already fills the
    // 16-MiB card: it places the single-ROM loader into an internal erased
    // 0xFF run instead of extending the image beyond 0x1000000.
    //
    // In that capture the selected slot is 0x00D97730.  The bytes immediately
    // before it show the erased run begins at 0x00D97728, so the manager's
    // chosen address is the first 16-byte-aligned location in that gap.
    //
    // Preserve all smaller-ROM behavior: this search is only used by the
    // single-ROM builder when appending the loader would exceed card capacity.
    size_t i = 0xC0;
    const size_t limit = std::min(rom.size(), MAX_CARD_IMAGE);

    while (i < limit) {
        while (i < limit && rom[i] != 0xFF)
            ++i;

        const size_t run_start = i;

        while (i < limit && rom[i] == 0xFF)
            ++i;

        const size_t run_end = i;
        if (run_end <= run_start)
            continue;

        // Single-ROM captures show the manager reserves a gap large enough for
        // the full multi-ROM loader footprint even though the single loader is
        // only 0x660 bytes. Tales has an earlier 0x65C4-byte FF run that is
        // large enough for 0x660 but smaller than 0x7080; EZ3Manager skips it
        // and chooses the next large run at 0xD49010. It then starts at the
        // *next* 16-byte boundary (0xD49020), not the run-start address itself.
        const size_t aligned =
            (run_start + 16u) & ~static_cast<size_t>(15u);
        const size_t reserve_size = std::max(required_size, MULTI_TEMPLATE_LEN);

        if (aligned <= run_end &&
            reserve_size <= run_end - aligned) {
            return static_cast<uint32_t>(aligned);
        }
    }

    return std::nullopt;
}

static size_t relocate_template(std::vector<uint8_t>& t,
                                uint32_t original_base,
                                uint32_t new_base)
{
    const uint32_t lo = GBA_ROM_BASE + original_base;
    const uint32_t hi = lo + static_cast<uint32_t>(t.size());
    const int64_t delta = static_cast<int64_t>(new_base) -
                          static_cast<int64_t>(original_base);

    size_t count = 0;

    // The two independent single-ROM captures prove that all required
    // relocation words are 4-byte aligned literals. Including `hi` is
    // important: the template contains pointers to its one-past-end address.
    for (size_t off = 0; off + 4 <= t.size(); off += 4) {
        const uint32_t v = read_le32(t.data() + off);
        if (v >= lo && v <= hi) {
            const uint32_t nv =
                static_cast<uint32_t>(static_cast<int64_t>(v) + delta);
            write_le32(t, off, nv);
            ++count;
        }
    }
    return count;
}

static void write_catalog_entry(std::vector<uint8_t>& t,
                                size_t off,
                                const RomInfo& r,
                                bool first)
{
    if (off + 28 > t.size())
        throw std::runtime_error("catalog entry is outside template");

    std::fill(t.begin() + static_cast<std::ptrdiff_t>(off),
              t.begin() + static_cast<std::ptrdiff_t>(off + 28),
              0x00);

    for (size_t i = 0; i < r.name.size() && i < 16; ++i)
        t[off + i] = static_cast<uint8_t>(r.name[i]);

    // Capture entry bytes 16..19:
    // GBA-Notepad => 00 00 00 07
    // PIANO/Bios  => 00 00 00 09
    const uint32_t type_field = static_cast<uint32_t>(r.entry_type) << 24;
    write_le32(t, off + 16, type_field);

    // Capture entry bytes 20..23:
    //   high 24 bits: ((byte_start / 2) << 8)
    //   low byte:     ROM mapping/config flag
    //
    // Captured SRAM cases use flag 3.  Both captured FLASH cases use flag 6:
    //   FFTA / FLASH512_V130 (16 MiB) -> 6
    //   Advance Wars / FLASH_V121 (8 MiB) -> 6
    // Therefore flag 6 is not a 128-Mbit-size special case.
    const uint32_t packed_start =
        ((r.start / 2u) << 8) | static_cast<uint32_t>(r.mapping_flag);

    write_le32(t, off + 20, packed_start);

    // The first ROM stores its original ARM branch target (0xC0 in all
    // supplied ROMs). Later ROMs store their byte start address.
    write_le32(t, off + 24,
               first ? r.original_entry_target : r.start);
}

static std::vector<uint8_t> build_single_image(std::vector<RomInfo>& roms,
                                               std::ostream& report)
{
    if (roms.size() != 1)
        throw std::runtime_error("single image builder requires exactly one ROM");

    auto t = decode_base64(kSingleTemplateB64);
    if (t.size() != SINGLE_TEMPLATE_LEN)
        throw std::runtime_error("single template decode length mismatch");

    RomInfo& r = roms[0];
    r.start = 0;

    const size_t meaningful_end = meaningful_rom_end(r.data);
    uint32_t loader_start = align_up_u32(static_cast<uint32_t>(meaningful_end), 16u);

    // Original-manager single-ROM captures reserve a multi-loader-sized FF
    // footprint even though only the 0x660-byte single loader is copied. Tales
    // has only 0x800 bytes of trailing FF, so EZ3Manager correctly ignores that
    // tail and uses the large internal gap at 0xD49010 instead.
    const size_t single_slot_reserve = std::max(t.size(), MULTI_TEMPLATE_LEN);

    bool loader_fits_in_padding = false;
    if (loader_start <= r.data.size() &&
        static_cast<uint64_t>(loader_start) + single_slot_reserve <= r.data.size()) {
        loader_fits_in_padding = std::all_of(
            r.data.begin() + static_cast<std::ptrdiff_t>(loader_start),
            r.data.begin() + static_cast<std::ptrdiff_t>(loader_start + single_slot_reserve),
            [](uint8_t b) { return b == 0xFF; });
    }

    bool loader_fits_in_internal_gap = false;
    bool loader_in_second_half = false;

    if (!loader_fits_in_padding) {
        if (r.data.size() == CARD_HALF_SIZE) {
            // Preserve FFTA first: the original manager uses its internal FF
            // gap even on a 256-Mbit cartridge.
            if (const auto internal = find_internal_ff_loader_slot(r.data, t.size())) {
                loader_start = *internal;
                loader_fits_in_internal_gap = true;
            } else {
                // fireemblem.pcap exact fallback for a full 16-MiB ROM with no
                // suitable internal FF hole.
                loader_start = static_cast<uint32_t>(CARD_HALF_SIZE + 0x10);
                loader_in_second_half = true;
            }
        } else {
            loader_start = align_up_u32(static_cast<uint32_t>(r.data.size()), 16u);
            if (static_cast<uint64_t>(loader_start) + t.size() > MAX_CARD_IMAGE) {
                const auto internal = find_internal_ff_loader_slot(r.data, t.size());
                if (!internal) {
                    throw std::runtime_error(
                        "single ROM fills the 32-MiB card and no internal FF "
                        "gap is large enough for the single-ROM loader");
                }
                loader_start = *internal;
                loader_fits_in_internal_gap = true;
            }
        }
    }

    const size_t reloc_count = relocate_template(t, SINGLE_TEMPLATE_BASE, loader_start);
    if (reloc_count != 13)
        throw std::runtime_error("unexpected single-template relocation count");

    write_le16(t, SINGLE_HEADER_OFF, 1);
    write_le16(t, SINGLE_HEADER_COUNT2_OFF, 1);

    write_catalog_entry(t, SINGLE_ENTRY_OFF, r, true);

    if (r.mapping_flag == 6 || r.mapping_flag == 7) {
        report << "FLASH catalog mapping: type "
                  << static_cast<unsigned>(r.entry_type)
                  << ", mapping flag "
                  << static_cast<unsigned>(r.mapping_flag)
                  << " (capture-derived)\n";
    }

    size_t image_size = std::max<size_t>(
        r.data.size(), static_cast<size_t>(loader_start) + t.size());
    if (loader_in_second_half)
        image_size = (image_size + 0xFFu) & ~static_cast<size_t>(0xFFu);

    if (image_size > MAX_CARD_IMAGE)
        throw std::runtime_error("single-ROM image exceeds 256-Mbit cartridge capacity");

    std::vector<uint8_t> image(image_size, 0xFF);
    std::copy(r.data.begin(), r.data.end(), image.begin());
    if (loader_in_second_half) {
        std::fill(image.begin() + static_cast<std::ptrdiff_t>(CARD_HALF_SIZE),
                  image.begin() + static_cast<std::ptrdiff_t>(loader_start),
                  0x00);
    }

    const uint32_t patched =
        ezfadvance::CartridgeFormat::makeArmBranch(loader_start);
    write_le32(image, 0, patched);
    std::copy(t.begin(), t.end(),
              image.begin() + static_cast<std::ptrdiff_t>(loader_start));

    report << "Single-ROM meaningful data end @ byte 0x"
              << std::hex << meaningful_end << std::dec << '\n';
    report << "Single-ROM loader @ byte 0x"
              << std::hex << loader_start << std::dec;
    if (loader_fits_in_padding)
        report << " (inside trailing FF padding)";
    else if (loader_fits_in_internal_gap)
        report << " (inside internal FF gap)";
    else if (loader_in_second_half)
        report << " (second 16-MiB half; fireemblem.pcap behavior)";
    report << '\n';

    return image;
}

static std::vector<uint8_t> build_multi_image(std::vector<RomInfo>& roms,
                                              std::ostream& report)
{
    if (roms.empty())
        throw std::runtime_error("multi-loader image builder requires at least one ROM");
    if (roms.size() > MULTI_CATALOG_MAX_ENTRIES) {
        std::ostringstream oss;
        oss << "multi-ROM catalog has " << MULTI_CATALOG_MAX_ENTRIES
            << " structural slots, but " << roms.size() << " ROMs were supplied";
        throw std::runtime_error(oss.str());
    }

    const std::vector<std::string> input_paths = [&]() {
        std::vector<std::string> v;
        v.reserve(roms.size());
        for (const auto& r : roms) v.push_back(r.path);
        return v;
    }();

    // piano-megamanz.pcap and 8_8_16MiB.pcap both prove that EZ3Manager does
    // not preserve insertion order. The observed rule is a stable descending
    // file-size order: larger ROMs move first, while equal-size ROMs retain
    // their original relative order.
    std::stable_sort(
        roms.begin(), roms.end(),
        [](const RomInfo& a, const RomInfo& b) {
            return a.data.size() > b.data.size();
        });

    bool reordered = false;
    for (size_t i = 0; i < roms.size(); ++i) {
        if (roms[i].path != input_paths[i]) {
            reordered = true;
            break;
        }
    }

    report << "\n========================================\n"
              << (roms.size() == 1
                      ? "EXPERIMENTAL ONE-ENTRY MULTI-LOADER PACKING\n"
                      : "CAPTURE-DERIVED MULTI-ROM PACKING\n")
              << "========================================\n"
              << "Ordering: stable descending ROM file size\n";
    if (reordered)
        report << "Input order changed to match original EZ3Manager packing.\n";
    else
        report << "Input order already matches original EZ3Manager packing.\n";

    // Place each ROM according to the size-class behavior exposed by the two
    // packing captures. The allocator advances by meaningful (non-trailing-FF)
    // data, then aligns the next ROM to that next ROM's size class. This lets a
    // smaller ROM reuse trailing FF padding without allowing a large ROM to
    // straddle a boundary that EZ3Manager itself avoids.
    uint64_t meaningful_cursor = 0;
    for (size_t i = 0; i < roms.size(); ++i) {
        const size_t meaningful = meaningful_rom_end(roms[i].data);
        const uint32_t alignment = multi_rom_size_class_alignment(roms[i].data.size());

        uint64_t start = 0;
        if (i != 0)
            start = align_up_u64(meaningful_cursor, alignment);

        if (start > UINT32_MAX || start + roms[i].data.size() > MAX_CARD_IMAGE) {
            std::ostringstream oss;
            oss << "multi-ROM placement exceeds 256-Mbit cartridge while placing "
                << roms[i].name;
            throw std::runtime_error(oss.str());
        }

        roms[i].start = static_cast<uint32_t>(start);
        meaningful_cursor = std::max<uint64_t>(
            meaningful_cursor, start + meaningful);

        report << "  #" << (i + 1) << " " << roms[i].name
                  << ": file 0x" << std::hex << roms[i].data.size()
                  << ", meaningful end +0x" << meaningful
                  << ", size-class align 0x" << alignment
                  << ", start 0x" << roms[i].start
                  << std::dec << '\n';
    }

    size_t base_image_size = 0;
    for (const auto& r : roms) {
        base_image_size = std::max<size_t>(
            base_image_size,
            static_cast<size_t>(r.start) + r.data.size());
    }
    if (base_image_size > MAX_CARD_IMAGE)
        throw std::runtime_error("packed ROM image exceeds 256-Mbit cartridge capacity");

    std::vector<uint8_t> image(base_image_size, 0xFF);

    // Copy in sorted/physical order. Any overlap is legal only where earlier
    // ROM bytes are erased FF padding; meaningful_cursor placement above is
    // designed to guarantee that property, but validate it explicitly.
    std::vector<uint8_t> occupied_non_ff(base_image_size, 0);
    for (const auto& r : roms) {
        const size_t base = r.start;
        for (size_t j = 0; j < r.data.size(); ++j) {
            const size_t dst = base + j;
            if (occupied_non_ff[dst] && r.data[j] != 0xFF) {
                std::ostringstream oss;
                oss << "multi-ROM packing would overlap meaningful ROM data at card byte 0x"
                    << std::hex << dst;
                throw std::runtime_error(oss.str());
            }
            if (r.data[j] != 0xFF)
                occupied_non_ff[dst] = 1;
            image[dst] = r.data[j];
        }
    }

    auto t = decode_base64(kMultiTemplateB64);
    if (t.size() != MULTI_TEMPLATE_LEN)
        throw std::runtime_error("multi template decode length mismatch");

    static_assert(MULTI_CAPTURE_GAP_OFF + MULTI_CAPTURE_GAP_BYTES.size()
                  <= MULTI_TEMPLATE_LEN,
                  "multi capture-gap patch must fit inside loader template");
    std::copy(MULTI_CAPTURE_GAP_BYTES.begin(),
              MULTI_CAPTURE_GAP_BYTES.end(),
              t.begin() + static_cast<std::ptrdiff_t>(MULTI_CAPTURE_GAP_OFF));

    size_t loader_copy_len = t.size();
    if (roms.size() == 2)
        loader_copy_len = MULTI_TWO_ROM_LEN;

    // Both new captures prove the loader is embedded in an existing erased
    // run when one is available: 0x2CC420 inside MegaManZ for MegaManZ+Piano,
    // and 0x15C2360 inside Advance Wars for FireEmblem+AdvanceWars+MegaManZ.
    uint32_t loader_start = 0;
    if (const auto slot = find_ff_slot_in_image(image, loader_copy_len)) {
        loader_start = *slot;
        report << "Loader placement: internal/trailing FF slot @ 0x"
                  << std::hex << loader_start << std::dec << '\n';
    } else {
        const uint64_t appended = align_up_u64(image.size(), 16u);
        if (appended + loader_copy_len > MAX_CARD_IMAGE)
            throw std::runtime_error(
                "no capture-compatible FF slot for multi-ROM loader and no card space to append it");
        loader_start = static_cast<uint32_t>(appended);
        image.resize(static_cast<size_t>(loader_start) + loader_copy_len, 0xFF);
        occupied_non_ff.resize(image.size(), 0);
        report << "Loader placement: appended @ 0x"
                  << std::hex << loader_start << std::dec
                  << " (no sufficiently large FF slot found)\n";
    }

    const size_t reloc_count =
        relocate_template(t, MULTI_TEMPLATE_BASE, loader_start);
    if (reloc_count != 125) {
        std::ostringstream oss;
        oss << "unexpected multi-template relocation count: "
            << reloc_count << " (expected 125)";
        throw std::runtime_error(oss.str());
    }

    write_le16(t, MULTI_HEADER_OFF,
               static_cast<uint16_t>(roms.size()));
    write_le16(t, MULTI_HEADER_OFF + 14,
               static_cast<uint16_t>(roms.size()));

    std::fill(
        t.begin() + static_cast<std::ptrdiff_t>(MULTI_ENTRY_OFF),
        t.begin() + static_cast<std::ptrdiff_t>(
            MULTI_ENTRY_OFF + MULTI_TEMPLATE_POPULATED_ENTRY_SLOTS * 28),
        0x00);

    for (size_t i = 0; i < roms.size(); ++i)
        write_catalog_entry(t, MULTI_ENTRY_OFF + i * 28, roms[i], i == 0);

    if (roms.size() == 2) {
        // Exact unused third-entry sentinel observed in piano-bios.pcap.
        const size_t unused = MULTI_ENTRY_OFF + 2 * 28;
        std::fill(t.begin() + static_cast<std::ptrdiff_t>(unused),
                  t.begin() + static_cast<std::ptrdiff_t>(unused + 28),
                  0x00);
        std::fill(t.begin() + static_cast<std::ptrdiff_t>(unused + 1),
                  t.begin() + static_cast<std::ptrdiff_t>(unused + 16),
                  0x20);

        std::fill(
            t.begin() + static_cast<std::ptrdiff_t>(
                MULTI_TWO_ROM_ERASED_TAIL_OFF),
            t.begin() + static_cast<std::ptrdiff_t>(MULTI_TWO_ROM_LEN),
            0xFF);
    }

    if (roms.size() >= 4) {
        // Capture-exact >=4-ROM tail from the independent four-, five-,
        // and six-ROM captures.
        static_assert(MULTI_FOUR_PLUS_ROM_ZERO_TAIL_OFF + MULTI_FOUR_PLUS_ROM_ZERO_TAIL_LEN
                      == MULTI_TEMPLATE_LEN,
                      ">=4-ROM zero tail must end at the loader boundary");
        std::fill(
            t.begin() + static_cast<std::ptrdiff_t>(MULTI_FOUR_PLUS_ROM_ZERO_TAIL_OFF),
            t.begin() + static_cast<std::ptrdiff_t>(MULTI_TEMPLATE_LEN),
            0x00);
    }

    if (static_cast<size_t>(loader_start) + loader_copy_len > image.size())
        image.resize(static_cast<size_t>(loader_start) + loader_copy_len, 0xFF);

    // Validate that the chosen loader slot did not overlap meaningful ROM data.
    for (size_t i = 0; i < loader_copy_len; ++i) {
        const size_t dst = static_cast<size_t>(loader_start) + i;
        if (dst < occupied_non_ff.size() && occupied_non_ff[dst]) {
            std::ostringstream oss;
            oss << "loader placement overlaps meaningful ROM data at card byte 0x"
                << std::hex << dst;
            throw std::runtime_error(oss.str());
        }
    }

    // Only physical/catalog ROM #1 is patched. Reordering therefore matters:
    // the branch is applied after stable sorting, exactly as the captures show.
    const uint32_t patched =
        ezfadvance::CartridgeFormat::makeArmBranch(loader_start);
    write_le32(image, 0, patched);

    std::copy(t.begin(),
              t.begin() + static_cast<std::ptrdiff_t>(loader_copy_len),
              image.begin() + static_cast<std::ptrdiff_t>(loader_start));

    report << "Multi-ROM loader/menu @ byte 0x"
              << std::hex << loader_start << std::dec << '\n';

    if (roms.size() == 1) {
        report << "Experimental one-entry multi-loader extent: 0x"
                  << std::hex << loader_copy_len
                  << " bytes; image end 0x" << image.size()
                  << std::dec << '\n';
    } else if (roms.size() == 2) {
        report << "Two-ROM capture-exact loader extent: 0x"
                  << std::hex << loader_copy_len
                  << " bytes; image end 0x" << image.size()
                  << std::dec << '\n';
    } else if (roms.size() >= 4) {
        report << roms.size()
                  << "-ROM capture-exact loader extent: 0x" << std::hex
                  << loader_copy_len << "; image end 0x" << image.size()
                  << std::dec << '\n';
    } else {
        report << "Three-ROM loader extent: 0x" << std::hex
                  << loader_copy_len << "; image end 0x" << image.size()
                  << std::dec << '\n';
    }

    return image;
}

} // namespace

bool CartridgeImageBuilder::build(std::vector<RomInfo>& roms,
                                  BuiltCartridgeImage& result,
                                  std::string& error,
                                  const CartridgeImageBuildOptions& options) const
{
    std::ostringstream report;
    const bool use_single_loader =
        roms.size() == 1 && !options.use_multi_loader_for_single_rom;
    result.bytes = use_single_loader
        ? build_single_image(roms, report)
        : build_multi_image(roms, report);
    result.report = report.str();
    if (result.bytes.size() > MAX_CARD_IMAGE) {
        std::ostringstream message;
        message << "Constructed image is 0x" << std::hex << result.bytes.size()
                << " bytes, exceeding the 256-Mbit cartridge capacity 0x"
                << MAX_CARD_IMAGE << std::dec << ".";
        error = message.str();
        return false;
    }
    const uint64_t minimum_programmed = std::max<uint64_t>(
        PROGRAM_BLOCK, static_cast<uint64_t>(result.bytes.size()));
    const uint64_t programmed = align_up_u64(minimum_programmed, 0x100u);
    if (programmed > MAX_CARD_IMAGE) {
        std::ostringstream message;
        message << "0x100-aligned programmed extent 0x" << std::hex
                << programmed << " exceeds the 256-Mbit cartridge capacity 0x"
                << MAX_CARD_IMAGE << std::dec << ".";
        error = message.str();
        return false;
    }
    result.programmed_size = static_cast<size_t>(programmed);
    result.bytes.resize(result.programmed_size, 0xFF);
    return true;
}

} // namespace ezfadvance
